version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
    - "27017:27017"
    volumes:
    - data:/data
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
#      - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
#      - ME_CONFIG_BASICAUTH_USERNAME=dev
#      - ME_CONFIG_BASICAUTH_PASSWORD=dev

    ports:
      - 8888:8081
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
# docker stack deploy -c stack.yml mongo (or docker-compose -f stack.yml up -d)