server:
  port: 8080

spring:
  application:
    name:
      museek
  profiles:
    active: developer
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      authentication-database: admin
      database: museek
      username: rootuser
      password: rootpass



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}