package com.giga.museek.bootstrap;

import com.giga.museek.documents.Brand;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class BrandLists2 {
    private List<Brand> brands;
    public BrandLists2() {
        brands = fillAllBrands1();

    }

    private List<Brand> fillAllBrands1() {

        return List.of(

                new Brand("ArtistPro"),
                new Brand("Artley"),
                new Brand("Artmann"),
                new Brand("Artonus"),
                new Brand("Arturia"),
                new Brand("Asahi"),
                new Brand("Asba"),
                new Brand("ASG Guitars"),
                new Brand("Ashbory Bass"),
                new Brand("Ashdown"),
                new Brand("Asher Guitars"),
                new Brand("Ashland"),
                new Brand("Ashley Mark"),
                new Brand("Ashly Audio"),
                new Brand("Ashton"),
                new Brand("Ask Video"),
                new Brand("ASS"),
                new Brand("Associated"),
                new Brand("Astatic by CAD"),
                new Brand("Astell&amp;Kern"),
                new Brand("Creative Technology"),
                new Brand("Creek"),
                new Brand("Creepnomore"),
                new Brand("Creepy Fingers Effects"),
                new Brand("Crest Audio"),
                new Brand("Crestline"),
                new Brand("Crestron"),
                new Brand("Crestwood"),
                new Brand("Critter &amp; Guitari"),
                new Brand("Cromwell"),
                new Brand("Crookwood"),
                new Brand("Croson"),
                new Brand("Crown"),
                new Brand("Crowther Audio"),
                new Brand("Crucianelli"),
                new Brand("Cruiser by Crafter"),
                new Brand("Crumar"),
                new Brand("Crusader Guitars"),
                new Brand("CTS"),
                new Brand("Cuenca"),
                new Brand("Curci"),
                new Brand("Curry"),
                new Brand("Curt Mangan"),
                new Brand("Curtis Novak"),
                new Brand("Cusack Effects"),
                new Brand("Custom Audio Electronics"),
                new Brand("Custom Electronics"),
                new Brand("Custom Shop Parts"),
                new Brand("Custom Tones"),
                new Brand("Custom77"),
                new Brand("CVL"),
                new Brand("Cwejman"),
                new Brand("Cyber Acoustics"),
                new Brand("Cycling 74"),
                new Brand("Cyclone Analogic"),
                new Brand("Cymatic Audio"),
                new Brand("Cymbal Crown"),
                new Brand("Cymbomute"),
                new Brand("Cympad"),
                new Brand("Cyril Morin"),
                new Brand("Czarcie Kopyto"),
                new Brand("D TAR"),
                new Brand("D&amp;B Audiotechnik"),
                new Brand("D&amp;R"),
                new Brand("D*A*M Differential Audio Manifestationz"),
                new Brand("D.A.V. Electronics"),
                new Brand("D.E.I. SYSTEM"),
                new Brand("DAD Dynamic Audio Device"),
                new Brand("D''Addario"),
                new Brand("Daddy Mojo"),
                new Brand("Dadi"),
                new Brand("Daewoo"),
                new Brand("Dag"),
                new Brand("Daila Percussions"),
                new Brand("Daion"),
                new Brand("Daisy Rock"),
                new Brand("Daito"),
                new Brand("Daking"),
                new Brand("Dale Forty"),
                new Brand("D''Alessandro"),
                new Brand("Dallapè"),
                new Brand("Dallas Arbiter"),
                new Brand("Dallas Rangemaster"),
                new Brand("DAM"),
                new Brand("Damage Control"),
                new Brand("Damon"),
                new Brand("Dampit"),
                new Brand("Dan Armstrong"),
                new Brand("Danca Audio"),
                new Brand("D''Andrea"),
                new Brand("Danelectro"),
                new Brand("D''Angelico Guitars"),
                new Brand("Dangelo Amplifiers"),
                new Brand("Dangerous Music"),
                new Brand("Daniele Giardina"),
                new Brand("Danmar"),
                new Brand("DAP Audio"),
                new Brand("Daphon"),
                new Brand("D''Aquisto"),
                new Brand("Darco"),
                new Brand("Darestone"),
                new Brand("Darkglass Electronics"),
                new Brand("DAS"),
                new Brand("Daslight"),
                new Brand("Dateq"),
                new Brand("Dava"),
                new Brand("Dave Guardala"),
                new Brand("Dave Hall Amplifiers"),
                new Brand("Dave Smith Instruments"),
                new Brand("David Allen Pickups"),
                new Brand("David Bray Amps"),
                new Brand("David Eden"),
                new Brand("David Gage"),
                new Brand("David Hite"),
                new Brand("David Naill"),
                new Brand("Davis Acoustic"),
                new Brand("Davoli"),
                new Brand("Dawn"),
                new Brand("Dawner Prince Electronic"),
                new Brand("Dayton Audio"),
                new Brand("DB Percussion"),
                new Brand("DB Technologies"),
                new Brand("DBS electronic"),
                new Brand("DBX"),
                new Brand("DBZ Guitars"),
                new Brand("DDA Console"),
                new Brand("DDrum"),
                new Brand("Ddt"),
                new Brand("De Armond"),
                new Brand("De Gier Guitars"),
                new Brand("De Haske Publications"),
                new Brand("De Salvo"),
                new Brand("De Sisti"),
                new Brand("Deagan"),
                new Brand("Dean"),
                new Brand("Dean Markley"),
                new Brand("Death by Audio"),
                new Brand("Decibel Eleven"),
                new Brand("Decksaver"),
                new Brand("Dee Jay Service"),
                new Brand("Deep"),
                new Brand("Deering"),
                new Brand("Defil"),
                new Brand("Definitive Technology"),
                new Brand("Defraia Guitars"),
                new Brand("DEG"),
                new Brand("Deimel Guitarworks"),
                new Brand("Delano"),
                new Brand("Delcam Audio"),
                new Brand("Dell"),
                new Brand("Della Noce"),
                new Brand("Delo Drums"),
                new Brand("Delson"),
                new Brand("DeltaLab"),
                new Brand("D''Em Crazy"),
                new Brand("Demeter Amplification"),
                new Brand("Denis Wick"),
                new Brand("Dennilu"),
                new Brand("Denon"),
                new Brand("Denon DJ"),
                new Brand("DeSalvo"),
                new Brand("Devi Ever"),
                new Brand("Devialet"),
                new Brand("Devine Entertainment"),
                new Brand("Deviser"),
                new Brand("Dexibell"),
                new Brand("DG De Gregorio"),
                new Brand("Di Berardino Drums"),
                new Brand("Di Giorgio"),
                new Brand("Di Leonardo"),
                new Brand("Di Zhao"),
                new Brand("Diago"),
                new Brand("Diamante"),
                new Brand("Diamond"),
                new Brand("Diapason"),
                new Brand("Diaz"),
                new Brand("Dickies"),
                new Brand("Didgeridoo Store"),
                new Brand("Dietmann"),
                new Brand("Diezel"),
                new Brand("Digico"),
                new Brand("Digidesign"),
                new Brand("Digigram"),
                new Brand("Digisynthetic"),
                new Brand("Digital Audio Denmark"),
                new Brand("Digital Audio Labs"),
                new Brand("Digital Music Corporation"),
                new Brand("Digital Music Doctor"),
                new Brand("Digital Redux"),
                new Brand("Digital Reference"),
                new Brand("DigiTech"),
                new Brand("Dikom"),
                new Brand("Dillion Guitars"),
                new Brand("DiMarzio"),
                new Brand("Dimavery"),
                new Brand("Dime Amplification"),
                new Brand("Dime Hardware"),
                new Brand("diMedici"),
                new Brand("Dingwall Guitars"),
                new Brand("Dino Baffetti"),
                new Brand("Dino''s Guitars"),
                new Brand("DiPinto"),
                new Brand("Direct Sound"),
                new Brand("Diril Cymbals"),
                new Brand("Dirty Boy Pedals"),
                new Brand("Disaster Area Amps"),
                new Brand("Discacciati"),
                new Brand("Discopiu"),
                new Brand("Disney"),
                new Brand("Disney by Washburn"),
                new Brand("Display and Play"),
                new Brand("Divided by 13"),
                new Brand("Dixon"),
                new Brand("DJ Flare"),
                new Brand("Dj Pro"),
                new Brand("DJ Qbert"),
                new Brand("DJ-Shield"),
                new Brand("DJ-Tech"),
                new Brand("Dls Effects"),
                new Brand("DM"),
                new Brand("DMC"),
                new Brand("DMRLCargo"),
                new Brand("DNA Analogic"),
                new Brand("Dobro"),
                new Brand("DocZac"),
                new Brand("DOD"),
                new Brand("Doepfer"),
                new Brand("Dogal"),
                new Brand("Doina"),
                new Brand("Dolmetsch"),
                new Brand("Dolnet"),
                new Brand("Dolphin''s Sound"),
                new Brand("Domus Musica"),
                new Brand("Donlis"),
                new Brand("Donner"),
                new Brand("Dophix"),
                new Brand("D''Orazio"),
                new Brand("Doreli"),
                new Brand("Dorfler"),
                new Brand("Dori"),
                new Brand("Dorrough"),
                new Brand("Dot on Shaft"),
                new Brand("Douglas Guitars"),
                new Brand("Dowina"),
                new Brand("Down 2 Earth"),
                new Brand("Dpa Microphones"),
                new Brand("DR Pro"),
                new Brand("DR Strings"),
                new Brand("Dr. Bohm"),
                new Brand("Dr. Dan''s"),
                new Brand("Dr. Green"),
                new Brand("Dr. Scientist"),
                new Brand("Dr. Z Amplification"),
                new Brand("Dr.J Effects"),
                new Brand("Dr.No Effects"),
                new Brand("Dragonfly"),
                new Brand("Dragonfly Clothing Company"),
                new Brand("Dragoon"),
                new Brand("Drake Mouthpieces"),
                new Brand("Drawmer"),
                new Brand("Dreadbox"),
                new Brand("Dream Cymbals"),
                new Brand("Dreamaker Amps"),
                new Brand("Dreambow"),
                new Brand("Dreamsongs Pickups"),
                new Brand("Driftwood Amps"),
                new Brand("Drive"),
                new Brand("Drum Art"),
                new Brand("Drum Fun"),
                new Brand("Drum One"),
                new Brand("Drum Os"),
                new Brand("Drum Pike"),
                new Brand("Drum Sound"),
                new Brand("Drum Tech"),
                new Brand("Drum Workshop"),
                new Brand("DrumCraft"),
                new Brand("Drumdial"),
                new Brand("DRUMM3R"),
                new Brand("Drummer''s Design"),
                new Brand("Drumometer"),
                new Brand("Drumstatic"),
                new Brand("Drybell"),
                new Brand("DTS Lighting Company"),
                new Brand("Duallist"),
                new Brand("Dudemusic"),
                new Brand("Duende"),
                new Brand("Duesenberg"),
                new Brand("Duke"),
                new Brand("Dukoff"),
                new Brand("Dumble"),
                new Brand("Dunbar"),
                new Brand("Duncan Designed"),
                new Brand("Duncan Performer"),
                new Brand("Dunlop"),
                new Brand("Dunnett"),
                new Brand("DuP"),
                new Brand("Dupont"),
                new Brand("Durham Electronics"),
                new Brand("Dusty Strings"),
                new Brand("DV Mark"),
                new Brand("Dvorak"),
                new Brand("DVR"),
                new Brand("DW"),
                new Brand("DW Drums"),
                new Brand("Dwarfcraft Devices"),
                new Brand("Dynacord"),
                new Brand("Dynarette"),
                new Brand("Dynasonics"),
                new Brand("Dynasty"),
                new Brand("Dynatone"),
                new Brand("Dynaudio"),
                new Brand("Dynaudio Acoustics"),
                new Brand("E Cords"),
                new Brand("E MU"),
                new Brand("E Mu Systems"),
                new Brand("E.C. Kerby"),
                new Brand("E.Energy"),
                new Brand("E3works"),
                new Brand("Eagle"),
                new Brand("Eagle Line"),
                new Brand("Eagle Mountain"),
                new Brand("Eagletone"),
                new Brand("EamLab"),
                new Brand("EAR SONICS"),
                new Brand("Ear Trumpet Labs"),
                new Brand("EAR Yoshino"),
                new Brand("Earlham"),
                new Brand("EarthQuaker Devices"),
                new Brand("Earthtone"),
                new Brand("earthworks"),
                new Brand("East Meets West"),
                new Brand("East UK"),
                new Brand("East West"),
                new Brand("Eastman"),
                new Brand("EastWest"),
                new Brand("Eastwood Guitars"),
                new Brand("Easy Play"),
                new Brand("EAW"),
                new Brand("EBO"),
                new Brand("E-Bow"),
                new Brand("EBS"),
                new Brand("Ebtech"),
                new Brand("Ec Pedals"),
                new Brand("Eccleshall"),
                new Brand("Echo"),
                new Brand("Echo Digital Audio"),
                new Brand("Echobel"),
                new Brand("Echolette"),
                new Brand("Echopark"),
                new Brand("Ecler"),
                new Brand("Eclipse"),
                new Brand("Eclipse Trumpets"),
                new Brand("Ecm"),
                new Brand("Ecorda"),
                new Brand("ECS"),
                new Brand("EdC Sound"),
                new Brand("Eddy Finn"),
                new Brand("Eden"),
                new Brand("Edicron"),
                new Brand("Edifier Speakers"),
                new Brand("Edirol"),
                new Brand("Editors Keys"),
                new Brand("Edward Dada"),
                new Brand("Edward Van Halen"),
                new Brand("Edwards Guitars"),
                new Brand("Edwards Trombones"),
                new Brand("Efesto Production"),
                new Brand("Effector 13"),
                new Brand("Effectrode"),
                new Brand("Effects Pedal Boutique"),
                new Brand("Effedot"),
                new Brand("Effettidiclara"),
                new Brand("Egmond Guitars"),
                new Brand("Egnater Amplification"),
                new Brand("Ego Lighting"),
                new Brand("Ego Sonoro"),
                new Brand("EICH Amplification"),
                new Brand("Eigenlabs"),
                new Brand("Eighteen Sound"),
                new Brand("Eiki"),
                new Brand("Eko"),
                new Brand("Eko Guitars"),
                new Brand("EKS"),
                new Brand("El Dorado"),
                new Brand("El Musico Loco"),
                new Brand("El Torres"),
                new Brand("Elation"),
                new Brand("Electra Guitars"),
                new Brand("Electric Piano Italia"),
                new Brand("Electrical Guitar Company"),
                new Brand("Electrix"),
                new Brand("Electro Faustus"),
                new Brand("Electro Harmonix"),
                new Brand("Electro Voice"),
                new Brand("Electrocompaniet"),
                new Brand("ElectroLead"),
                new Brand("Electronic Orange"),
                new Brand("Elektron"),
                new Brand("Elena Soprani"),
                new Brand("Elettronica Legend"),
                new Brand("Eleuke"),
                new Brand("Eleven Electrix"),
                new Brand("Elgam"),
                new Brand("e-licktronic"),
                new Brand("Eliminator"),
                new Brand("Eliminator Lighting"),
                new Brand("Elite Core"),
                new Brand("Elite Tone"),
                new Brand("Elixir"),
                new Brand("Elka"),
                new Brand("Elkavox"),
                new Brand("Elkhart"),
                new Brand("EllediSound"),
                new Brand("Elli-Sound"),
                new Brand("Elmwood Amps"),
                new Brand("Elrick"),
                new Brand("Elysia"),
                new Brand("EM Books"),
                new Brand("EM Winston"),
                new Brand("Emagic"),
                new Brand("Emanating Fist Electronics"),
                new Brand("Embergher"),
                new Brand("eMedia"),
                new Brand("Emerson"),
                new Brand("Emes"),
                new Brand("EMG"),
                new Brand("Eminence"),
                new Brand("Eminent"),
                new Brand("Emma"),
                new Brand("Emma Electronic"),
                new Brand("Emo Systems"),
                new Brand("Emperion Guitars"),
                new Brand("Empire Media"),
                new Brand("Empirical Labs"),
                new Brand("Empress"),
                new Brand("EMS"),
                new Brand("Emt"),
                new Brand("Emu"),
                new Brand("Encore"),
                new Brand("Endangered Audio Research"),
                new Brand("Endorphin.es"),
                new Brand("Endust"),
                new Brand("Energy"),
                new Brand("Engelhardt"),
                new Brand("Engineered Case Manufacturers"),
                new Brand("Engl"),
                new Brand("Engl Amps"),
                new Brand("Eno Pedals"),
                new Brand("Ensoniq"),
                new Brand("Enttec"),
                new Brand("Entwistle Custom Pickups"),
                new Brand("Eowave"),
                new Brand("Epa Sound"),
                new Brand("EPE"),
                new Brand("Epic"),
                new Brand("Epicure Speakers"),
                new Brand("Epifani"),
                new Brand("Epiphone"),
                new Brand("Epm Corporation"),
                new Brand("Epos Acoustics"),
                new Brand("Epson"),
                new Brand("Equator Audio"),
                new Brand("Erard"),
                new Brand("Ergoplay"),
                new Brand("Erica Synths"),
                new Brand("Erjk"),
                new Brand("Ernie Ball"),
                new Brand("Ernst Kaps"),
                new Brand("E-ROS"),
                new Brand("Esarc"),
                new Brand("Esh Bass"),
                new Brand("ESI"),
                new Brand("ESI Professional"),
                new Brand("Esio Audio"),
                new Brand("ESM Mouthpieces"),
                new Brand("Eso Mixer"),
                new Brand("ESP"),
                new Brand("Espana"),
                new Brand("Ess"),
                new Brand("ESS Electronic Sound Solution"),
                new Brand("Essetipicks"),
                new Brand("Essex Pianos"),
                new Brand("Esteban"),
                new Brand("Estephan"),
                new Brand("Esteve"),
                new Brand("Estive"),
                new Brand("Estonia Pianos"),
                new Brand("ETA Systems"),
                new Brand("ETC"),
                new Brand("Etek"),
                new Brand("Ethos Overdrive"),
                new Brand("Etoile"),
                new Brand("Euphonic Audio"),
                new Brand("Euphonix"),
                new Brand("Eurocable"),
                new Brand("Eurocases"),
                new Brand("Eurolegno"),
                new Brand("Eurolite"),
                new Brand("Euromet"),
                new Brand("Europoint"),
                new Brand("Eurotruss"),
                new Brand("Euterpe"),
                new Brand("Evandale"),
                new Brand("Evans"),
                new Brand("Eve Audio"),
                new Brand("Event"),
                new Brand("Eventide"),
                new Brand("Everly"),
                new Brand("Evertune"),
                new Brand("EVH"),
                new Brand("Evidence Audio"),
                new Brand("EvoLight"),
                new Brand("Evolution"),
                new Brand("E-Wave"),
                new Brand("Ews"),
                new Brand("Excalibur"),
                new Brand("Excelsior"),
                new Brand("Exclusive"),
                new Brand("ExEf"),
                new Brand("E-Xence"),
                new Brand("Expansion Tank"),
                new Brand("Expert Sleepers"),
                new Brand("Exploraudio"),
                new Brand("Exposure"),
                new Brand("Extreme"),
                new Brand("Extreme Sound"),
                new Brand("EZ Dupe"),
                new Brand("F Bass"),
                new Brand("F.E. Olds"),
                new Brand("F.lli Alessandrini"),
                new Brand("f.lli Vaccari"),
                new Brand("F.Lorée"),
                new Brand("Faber German Guitar Parts"),
                new Brand("Fable Sounds"),
                new Brand("Faby"),
                new Brand("Faceless FX"),
                new Brand("Facelift"),
                new Brand("Factory Guitars"),
                new Brand("Factory Metal Percussion"),
                new Brand("Facus"),
                new Brand("Faderfox"),
                new Brand("Fahrenheit"),
                new Brand("FAIRBANKS GUITARS"),
                new Brand("Fairfield Circuitry"),
                new Brand("Fairmont"),
                new Brand("FaitalPRO"),
                new Brand("Faith Guitars"),
                new Brand("Fal"),
                new Brand("Falcon"),
                new Brand("Famc"),
                new Brand("Fame"),
                new Brand("Fancy Pans"),
                new Brand("Fane"),
                new Brand("Fanfoni"),
                new Brand("Fanndec"),
                new Brand("Fano Guitars"),
                new Brand("Fantek"),
                new Brand("Fantini Accordions"),
                new Brand("Fantom"),
                new Brand("Fantoni"),
                new Brand("FarEast"),
                new Brand("Farfisa"),
                new Brand("Fargen Amps"),
                new Brand("Farida Guitars"),
                new Brand("Farley''s"),
                new Brand("Fasch"),
                new Brand("Fast Axe"),
                new Brand("Fat Congas"),
                new Brand("Fatar"),
                new Brand("Fattoria Mendoza"),
                new Brand("Favored Nations"),
                new Brand("Faxx"),
                new Brand("FBG Fatboy Guitars"),
                new Brand("FBT"),
                new Brand("Fclef"),
                new Brand("Fdb Audio"),
                new Brand("FEA Labs"),
                new Brand("Featherweight"),
                new Brand("Feeldrum"),
                new Brand("Feeltune"),
                new Brand("Fender"),
                new Brand("Fender Custom Shop Apparel"),
                new Brand("Fender Footwear"),
                new Brand("Fenix"),
                new Brand("Fenton"),
                new Brand("Fernandes"),
                new Brand("Ferrara"),
                new Brand("Ferrarotti"),
                new Brand("Ferrarotti Chitarre"),
                new Brand("Ferrofish"),
                new Brand("Feurich"),
                new Brand("Fever"),
                new Brand("Ffalstaff"),
                new Brand("FGN Guitars"),
                new Brand("FIAS Stradella"),
                new Brand("Fibes"),
                new Brand("Fibracell"),
                new Brand("Fides"),
                new Brand("FiiO"),
                new Brand("Fine Guitars"),
                new Brand("Fine Resophonic Guitars"),
                new Brand("Finger Fitness"),
                new Brand("Fingerease"),
                new Brand("Fingerweights"),
                new Brand("Finhol"),
                new Brand("FIP (fabbrica italiana pianoforti)"),
                new Brand("First Act"),
                new Brand("Fisart"),
                new Brand("Fisher"),
                new Brand("Fishman"),
                new Brand("Five-O by Montarbo"),
                new Brand("Fivre"),
                new Brand("Flame"),
                new Brand("Flametone"),
                new Brand("Flash"),
                new Brand("Flatiron"),
                new Brand("Flaxwood"),
                new Brand("Flea Bass"),
                new Brand("Flea Market Music"),
                new Brand("Fleta"),
                new Brand("FlexWaves"),
                new Brand("Flight"),
                new Brand("Flip Oakes Wild Thing"),
                new Brand("Flix"),
                new Brand("Floda Guitars"),
                new Brand("Florea"),
                new Brand("Florencia"),
                new Brand("Floret"),
                new Brand("Floyd Rose"),
                new Brand("Fluid Audio"),
                new Brand("Flux"),
                new Brand("FMR"),
                new Brand("Focal"),
                new Brand("FocGear"),
                new Brand("Focusrite"),
                new Brand("Fodera"),
                new Brand("Fohhn"),
                new Brand("Fom"),
                new Brand("Fontanot"),
                new Brand("Formanta"),
                new Brand("Formula B"),
                new Brand("Formula Sound"),
                new Brand("Forssell Technologies"),
                new Brand("Fortin"),
                new Brand("Fostex"),
                new Brand("Fox"),
                new Brand("FoxGear"),
                new Brand("Foxpedal"),
                new Brand("FoxRox"),
                new Brand("Foxx"),
                new Brand("Fp Group"),
                new Brand("FP Professional Cases"),
                new Brand("FPD Drums"),
                new Brand("F-Pedals"),
                new Brand("Fractal Audio"),
                new Brand("Framer"),
                new Brand("Frameworks Guitars"),
                new Brand("Framez"),
                new Brand("Framus"),
                new Brand("FRANCK BICHON"),
                new Brand("Francois Louis"),
                new Brand("Franklin Strap"),
                new Brand("Frantone"),
                new Brand("Franz Kirschnek"),
                new Brand("Frap Tools"),
                new Brand("Frate Precision"),
                new Brand("Fratelli Crosio"),
                new Brand("Fratelli Crosio Stradella"),
                new Brand("Fratelli Patricola"),
                new Brand("Fredenstein"),
                new Brand("Frederick Hemke"),
                new Brand("Fredric Effects"),
                new Brand("Free the Tone"),
                new Brand("FreeFloat"),
                new Brand("Freehand"),
                new Brand("Freekish Blues"),
                new Brand("Frenzel Amps"),
                new Brand("Frequency Central"),
                new Brand("Fret King"),
                new Brand("FretLight Guitars"),
                new Brand("Fretlord"),
                new Brand("Fridgebuzzz"),
                new Brand("Friedman Amplification"),
                new Brand("Frontalini"),
                new Brand("Frontier Design"),
                new Brand("Frontier Design Group"),
                new Brand("FrontStage"),
                new Brand("Frostwave"),
                new Brand("Frudua"),
                new Brand("Fryer Guitars"),
                new Brand("Fryette"),
                new Brand("Fuchs"),
                new Brand("Fujiha"),
                new Brand("Fulltone"),
                new Brand("Fun Generation"),
                new Brand("Funktion-One"),
                new Brand("Furch"),
                new Brand("Furcht &amp; Söhne"),
                new Brand("Furlanetto"),
                new Brand("Furman"),
                new Brand("Furstein"),
                new Brand("Fusco Guitars"),
                new Brand("Fusion"),
                new Brand("Future Retro"),
                new Brand("Future Sonics"),
                new Brand("Futurelight"),
                new Brand("FX"),
                new Brand("FX Case"),
                new Brand("FXpansion"),
                new Brand("FYRD"),
                new Brand("G Force"),
                new Brand("G Lobal"),
                new Brand("G&amp;BL"),
                new Brand("G&amp;L"),
                new Brand("G&amp;P"),
                new Brand("G. Schirmer"),
                new Brand("G.Art"),
                new Brand("G.I.S."),
                new Brand("G2D"),
                new Brand("G7th"),
                new Brand("Gabriel Sound Garage"),
                new Brand("Gain by FGN"),
                new Brand("Galactron"),
                new Brand("Galanti"),
                new Brand("Galanti Classic Organs"),
                new Brand("Galaxy"),
                new Brand("Galaxy Audio"),
                new Brand("Galileo"),
                new Brand("Gallagher Guitars"),
                new Brand("Galli"),
                new Brand("Gallien Krueger"),
                new Brand("Gallinotti"),
                new Brand("Galotta"),
                new Brand("Galveston Guitars"),
                new Brand("Garbujo Guitars"),
                new Brand("Gard"),
                new Brand("Garrard"),
                new Brand("Garrison"),
                new Brand("Garritan"),
                new Brand("Gary Hurst"),
                new Brand("Gary Sugal"),
                new Brand("Gaskell Guitars"),
                new Brand("Gato"),
                new Brand("Gator"),
                new Brand("Gatt Audio"),
                new Brand("Gaucho"),
                new Brand("Gauger Percussion"),
                new Brand("Gauss"),
                new Brand("Gaveau"),
                new Brand("Gavio"),
                new Brand("Gawharet El Fan"),
                new Brand("Gazley"),
                new Brand("GBC"),
                new Brand("GDE"),
                new Brand("Gear One"),
                new Brand("Gear4music"),
                new Brand("Gebr. Alexander mainz"),
                new Brand("GeekMacDaddy Pedals"),
                new Brand("Geloso"),
                new Brand("Gem"),
                new Brand("Gem Sound"),
                new Brand("Gembird"),
                new Brand("Gemeinhardt"),
                new Brand("Gemini"),
                new Brand("Gemini DJ"),
                new Brand("Genalex"),
                new Brand("Genelec"),
                new Brand("General Electric"),
                new Brand("General Music"),
                new Brand("General Rohren"),
                new Brand("Genesis"),
                new Brand("Genius"),
                new Brand("Genz Benz"),
                new Brand("Genzler"),
                new Brand("George Dennis"),
                new Brand("George L"),
                new Brand("George L''s"),
                new Brand("George Way Drums"),
                new Brand("German Light Products"),
                new Brand("Germino"),
                new Brand("Get''m Get''m"),
                new Brand("Getzen"),
                new Brand("Gewa"),
                new Brand("Geyer"),
                new Brand("GFI System"),
                new Brand("GFO Flight Cases"),
                new Brand("GForce"),
                new Brand("GFS electronics"),
                new Brand("GFS Pickups"),
                new Brand("GGP Sound"),
                new Brand("Gherson"),
                new Brand("GHS"),
                new Brand("GHS Strings"),
                new Brand("Giannini"),
                new Brand("Giardinelli"),
                new Brand("Gibraltar"),
                new Brand("Gibson"),
                new Brand("Gibson Custom Shop"),
                new Brand("Gig"),
                new Brand("Gig FX"),
                new Brand("Gig Skinz"),
                new Brand("Gigliotti"),
                new Brand("Gigrig"),
                new Brand("Gik Acoustics"),
                new Brand("Gil Yaron"),
                new Brand("Giovanetti Hand Wired"),
                new Brand("Gitane"),
                new Brand("Giulietti Fisarmoniche"),
                new Brand("Giussani"),
                new Brand("Giustozzi"),
                new Brand("Gkg Gary Kramer Guitars"),
                new Brand("G-Lab"),
                new Brand("Glaesel"),
                new Brand("Glaresoft"),
                new Brand("Glass Master"),
                new Brand("Glasser"),
                new Brand("GLB Sound"),
                new Brand("Glendale"),
                new Brand("Glider"),
                new Brand("Global Audio by CAD"),
                new Brand("Global Truss"),
                new Brand("Glockenklang"),
                new Brand("Glorious"),
                new Brand("GLX Lighting"),
                new Brand("GLX Pedals"),
                new Brand("Glyph"),
                new Brand("GMedia Music"),
                new Brand("GML"),
                new Brand("Gmp Guitars"),
                new Brand("GMS"),
                new Brand("GNG Guitars"),
                new Brand("GNI Pedals"),
                new Brand("Godin"),
                new Brand("Godlyke"),
                new Brand("Godvinez"),
                new Brand("Godwin Guitars"),
                new Brand("Godwin Organs"),
                new Brand("Goedrum"),
                new Brand("GoGo Tuners"),
                new Brand("Goja"),
                new Brand("Gold Line"),
                new Brand("Gold Star"),
                new Brand("Gold Tone"),
                new Brand("Golden Age"),
                new Brand("Golden Cup"),
                new Brand("Golden Gate"),
                new Brand("Golden Sound"),
                new Brand("Golden Ton"),
                new Brand("Golden Touch"),
                new Brand("Goldo"),
                new Brand("Goldpoint"),
                new Brand("Goldsound"),
                new Brand("Goldtone"),
                new Brand("Goldwood"),
                new Brand("GOLEM instruments"),
                new Brand("Goliath Studio"),
                new Brand("Gon Bops"),
                new Brand("Gonzales"),
                new Brand("Goodmans"),
                new Brand("Goodsell Amplifier"),
                new Brand("Goosoniqueworx"),
                new Brand("Gope"),
                new Brand("Gordius"),
                new Brand("Gordon Smith"),
                new Brand("Gorilla Snot"),
                new Brand("Görs &amp; Kallmann"),
                new Brand("Gotoh"),
                new Brand("Gower"),
                new Brand("GR Basses"),
                new Brand("GR Mouthpieces"),
                new Brand("Grace Design"),
                new Brand("Grado"),
                new Brand("Graph Tech"),
                new Brand("Grassi"),
                new Brand("Gravity"),
                new Brand("GRBASS"),
                new Brand("GRCustomize"),
                new Brand("Great Divide Guitar"),
                new Brand("Great River Electronics"),
                new Brand("Greco"),
                new Brand("Greedtone"),
                new Brand("Greenback"),
                new Brand("Greenhouse Effects"),
                new Brand("Greenwich"),
                new Brand("Greer Amps"),
                new Brand("Greg Bennett"),
                new Brand("Greg Black"),
                new Brand("Gretsch"),
                new Brand("Gretsch Drums"),
                new Brand("Gretsch Guitars"),
                new Brand("GreyDressedBoy"),
                new Brand("Griego Mouthpieces"),
                new Brand("Gripmaster"),
                new Brand("Griven"),
                new Brand("Groove Tube"),
                new Brand("Groove Tubes"),
                new Brand("Groovster Strings"),
                new Brand("Grosh Guitars"),
                new Brand("Grossman Music"),
                new Brand("Grotrian Steinweg"),
                new Brand("Grover"),
                new Brand("Grover Trophy"),
                new Brand("Grp Synthesizer"),
                new Brand("GRP Synthesizers"),
                new Brand("GRS"),
                new Brand("Grundig"),
                new Brand("Gruv Gear"),
                new Brand("Gryphon Audio"),
                new Brand("GS Light"),
                new Brand("GSA Audio"),
                new Brand("GTX Guitar"),
                new Brand("Guanex"),
                new Brand("Guardala"),
                new Brand("Guerrini"),
                new Brand("Guil"),
                new Brand("Guild"),
                new Brand("Guillemot"),
                new Brand("Guistar Picks"),
                new Brand("Guitar 411"),
                new Brand("Guitar Center"),
                new Brand("Guitar Fetish"),
                new Brand("Guitar Heads"),
                new Brand("Guitar Hero"),
                new Brand("Guitar Research"),
                new Brand("Guitar Rings"),
                new Brand("Guitar Tech"),
                new Brand("Guitares Donadini"),
                new Brand("Gulbransen"),
                new Brand("Gullansky Lab"),
                new Brand("Gurus"),
                new Brand("Gut-a-Like"),
                new Brand("Guvnor Guitars"),
                new Brand("Guyatone"),
                new Brand("Guzauski-Swist"),
                new Brand("GW Guitars"),
                new Brand("H&amp;S"),
                new Brand("H.J. Bernstein"),
                new Brand("Haagston"),
                new Brand("Haar Guitars"),
                new Brand("Haeussel"),
                new Brand("Hafler"),
                new Brand("Hagstrom"),
                new Brand("Hahn Guitars"),
                new Brand("Hal Leonard"),
                new Brand("Halifax"),
                new Brand("Hall"),
                new Brand("Hallmark"),
                new Brand("Halo Guitars"),
                new Brand("Hamer"),
                new Brand("Hamichord"),
                new Brand("Hamilton Stands"),
                new Brand("Hammerax"),
                new Brand("Hammig Flutes"),
                new Brand("Hammig Philipp"),
                new Brand("Hammond"),
                new Brand("Hand Crafted Labs"),
                new Brand("HandHeld Sound"),
                new Brand("Hand-i wood"),
                new Brand("Handmade"),
                new Brand("Hanika Guitars"),
                new Brand("Hannabach"),
                new Brand("Hans Hoyer"),
                new Brand("Hans Mayer"),
                new Brand("Hansenfutz"),
                new Brand("Hao"),
                new Brand("Hapi"),
                new Brand("Harbeth"),
                new Brand("Harbinger"),
                new Brand("Hardcase"),
                new Brand("HardWear"),
                new Brand("HardWire"),
                new Brand("Hardy"),
                new Brand("Harley Benton"),
                new Brand("Harman Kardon"),
                new Brand("Harmon"),
                new Brand("Harmonic Design"),
                new Brand("Harmonic Vision"),
                new Brand("HarmonicaLessons.com"),
                new Brand("Harmony Guitars")

        );
    }
}
