package com.giga.museek.bootstrap;

import com.giga.museek.documents.Brand;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class BrandLists3 {
    private  List<Brand> brands;
    public BrandLists3() {
        brands = fillAllBrands1();

    }

    private List<Brand> fillAllBrands1() {

        return List.of(

                new Brand("Harper"),
                new Brand("HarpGear Amplification"),
                new Brand("Harpsicle Harps"),
                new Brand("Harptone"),
                new Brand("Harrelson Trumpets"),
                new Brand("Harrier"),
                new Brand("Harrison Music Education Systems"),
                new Brand("Harry Benton"),
                new Brand("Harry Pedler"),
                new Brand("Harsan Mihalia"),
                new Brand("Hart Dynamics"),
                new Brand("Hartke"),
                new Brand("Hartman Pedals"),
                new Brand("Hartmann"),
                new Brand("Harvest Bags"),
                new Brand("Hauptwerk"),
                new Brand("Hawkes &amp; Son"),
                new Brand("Hawthorne by Walden"),
                new Brand("Hayden Amplifiers"),
                new Brand("Hayman"),
                new Brand("Haynes"),
                new Brand("Haywire Custom Guitars"),
                new Brand("HBE"),
                new Brand("Headfx"),
                new Brand("Headliner"),
                new Brand("Headrush"),
                new Brand("Headstrong Amplifiers"),
                new Brand("Headway"),
                new Brand("Hear Technologies"),
                new Brand("Hearos"),
                new Brand("Heartfield"),
                new Brand("Heavy Electronics"),
                new Brand("Heckel"),
                new Brand("Hedgehog Stompboxes"),
                new Brand("Heet Sound"),
                new Brand("Heil Sound"),
                new Brand("Helin"),
                new Brand("Helios Electronics Ltd"),
                new Brand("Hemingway Digital Pianos"),
                new Brand("Hennessey Guitar Parts"),
                new Brand("Henriksen"),
                new Brand("Henry Red Heller"),
                new Brand("Herco"),
                new Brand("Hercules"),
                new Brand("Hercules Stands"),
                new Brand("Herda Guitars"),
                new Brand("Heritage"),
                new Brand("Hermann"),
                new Brand("Hermida Audio"),
                new Brand("Hernals Tokyo"),
                new Brand("Hero"),
                new Brand("Hertz"),
                new Brand("Hesu"),
                new Brand("Hetman"),
                new Brand("Hevos"),
                new Brand("Hexe"),
                new Brand("Hexinverter Electronique"),
                new Brand("HH Electronic"),
                new Brand("HHB"),
                new Brand("Hi-Case"),
                new Brand("Hicon"),
                new Brand("Hidersine"),
                new Brand("HifiMan"),
                new Brand("High End Systems"),
                new Brand("High Spirits"),
                new Brand("Highwood"),
                new Brand("Higlander"),
                new Brand("Hijos de Vincente Tatay"),
                new Brand("Hill"),
                new Brand("Hillwood"),
                new Brand("Himmelstrutz"),
                new Brand("HiPercussion"),
                new Brand("Hipshot"),
                new Brand("Hirsbrunner"),
                new Brand("Hiscox Cases"),
                new Brand("Hitachi"),
                new Brand("Hitec Audio"),
                new Brand("Hiwatt"),
                new Brand("HK Audio"),
                new Brand("HK-Instruments"),
                new Brand("Hls Audio"),
                new Brand("Hodge"),
                new Brand("Hoepli"),
                new Brand("Hoffmann &amp; Kuhne"),
                new Brand("Hofmann &amp; Czerny"),
                new Brand("Hofmann Wien"),
                new Brand("Hofner"),
                new Brand("Hohner"),
                new Brand("Holling &amp; Spangenberg"),
                new Brand("Hollywood"),
                new Brand("Hologram Electronics"),
                new Brand("Holophone"),
                new Brand("Holton"),
                new Brand("Homebrew Electronics"),
                new Brand("Homespun"),
                new Brand("Hondo"),
                new Brand("Honsuy"),
                new Brand("Hope Lab"),
                new Brand("Hopf"),
                new Brand("Hora"),
                new Brand("Horizon"),
                new Brand("Hornby Skewes"),
                new Brand("Hornets"),
                new Brand("Horngacher"),
                new Brand("Horugel"),
                new Brand("Hosa"),
                new Brand("Hosco"),
                new Brand("Hoshino"),
                new Brand("Hosiden"),
                new Brand("Hot Cabs"),
                new Brand("Hot Licks"),
                new Brand("Hot Picks"),
                new Brand("Hot Sticks"),
                new Brand("Hotone"),
                new Brand("House of Blues"),
                new Brand("House of Troy"),
                new Brand("Houston Publishing"),
                new Brand("Howarth"),
                new Brand("Hoyer"),
                new Brand("HP"),
                new Brand("HQ Percussion"),
                new Brand("HQ Power"),
                new Brand("HQRP"),
                new Brand("Hranov"),
                new Brand("HRK"),
                new Brand("Hsinghai Piano"),
                new Brand("Htx Guitars"),
                new Brand("Hub van Laar"),
                new Brand("Hubschen"),
                new Brand("Hudson Electronics"),
                new Brand("Hudson Music"),
                new Brand("Hughes &amp; Kettner"),
                new Brand("Huller"),
                new Brand("Hulton Archive"),
                new Brand("Human Base"),
                new Brand("Human Gear"),
                new Brand("Humes &amp; Berg"),
                new Brand("Humfree"),
                new Brand("Humfrees"),
                new Brand("Humicase"),
                new Brand("Hunday Guitars"),
                new Brand("Hupfeld"),
                new Brand("Huss &amp; Dalton"),
                new Brand("Hutchins Guitars"),
                new Brand("Huttl"),
                new Brand("HXM"),
                new Brand("HyperSynth"),
                new Brand("Ial Sound"),
                new Brand("Ianiro"),
                new Brand("Ianni Organetti"),
                new Brand("Ibach"),
                new Brand("Ibanez"),
                new Brand("Ibiza"),
                new Brand("Ice Pix"),
                new Brand("IceScream Pedals"),
                new Brand("Icon"),
                new Brand("iConnectivity"),
                new Brand("iFi Audio"),
                new Brand("iGIG Cases"),
                new Brand("IGS Audio"),
                new Brand("IK Multimedia"),
                new Brand("iKey Audio"),
                new Brand("iko case"),
                new Brand("ILIO"),
                new Brand("IMAGE LINE"),
                new Brand("IMG Stage Line"),
                new Brand("Inaki Sebastian"),
                new Brand("Incagnoli"),
                new Brand("INDERBINEN"),
                new Brand("India Street Percussion"),
                new Brand("Indiana Line"),
                new Brand("Indie Guitars"),
                new Brand("Industrialectric"),
                new Brand("Infinity"),
                new Brand("Infinity Guitars"),
                new Brand("Ingram Sherman"),
                new Brand("Inima"),
                new Brand("Inkel"),
                new Brand("Innerclock Systems"),
                new Brand("Innovative Music Systems"),
                new Brand("Innovative Percussion"),
                new Brand("Input Logic"),
                new Brand("i-nstruments"),
                new Brand("Integrity Music"),
                new Brand("Intek"),
                new Brand("Intellijel"),
                new Brand("Intellitouch"),
                new Brand("Inter-M"),
                new Brand("International Music Company"),
                new Brand("International Sound"),
                new Brand("Intimidation"),
                new Brand("Involight"),
                new Brand("Inward Connections"),
                new Brand("Ion Audio"),
                new Brand("IPL"),
                new Brand("iPlayMusic"),
                new Brand("IQS"),
                new Brand("Iron Ether"),
                new Brand("Ironbridge Electronics"),
                new Brand("Ironess USA"),
                new Brand("Irongear"),
                new Brand("Islander Ukulele"),
                new Brand("Isoacoustic"),
                new Brand("iSong"),
                new Brand("IsoNode Pro"),
                new Brand("ISP Technologies"),
                new Brand("I-Spira"),
                new Brand("Istanbul"),
                new Brand("Italia"),
                new Brand("Italian Stage"),
                new Brand("ITBEATS"),
                new Brand("iZotope"),
                new Brand("J&amp;D Guitars"),
                new Brand("J&amp;H"),
                new Brand("J.Michael"),
                new Brand("J.Rockett Audio Designs"),
                new Brand("Jabra"),
                new Brand("Jacaranda"),
                new Brand("Jack Daniel''s"),
                new Brand("Jack Deville Electronics"),
                new Brand("Jackson"),
                new Brand("Jackson Audio"),
                new Brand("Jacoland"),
                new Brand("Jacques"),
                new Brand("Jacques Capelle"),
                new Brand("Jad&amp;Freer"),
                new Brand("Jade Audio"),
                new Brand("Jaden Rose Guitars"),
                new Brand("Jaeger"),
                new Brand("Jakob Winter"),
                new Brand("Jam Hub"),
                new Brand("Jam Pedals"),
                new Brand("Jambone"),
                new Brand("JAMedia"),
                new Brand("James Goodall"),
                new Brand("James Neligan"),
                new Brand("James Trussart Guitars"),
                new Brand("Jamey Aebersold"),
                new Brand("Jam-Mate"),
                new Brand("Jammin"),
                new Brand("Jamo"),
                new Brand("JamStands by Ultimate Support"),
                new Brand("Janagy"),
                new Brand("JanAid Guitars"),
                new Brand("Jands"),
                new Brand("JangleBox"),
                new Brand("Jarre Technologies"),
                new Brand("Jasmine by Takamine"),
                new Brand("Jaspers"),
                new Brand("Jay Haide Violins"),
                new Brand("Jay Turser"),
                new Brand("Jaydee"),
                new Brand("Jaytec"),
                new Brand("Jazzkat"),
                new Brand("JazzLab"),
                new Brand("JazzMutant"),
                new Brand("JB Lighting"),
                new Brand("JB Systems"),
                new Brand("JBE Pickups"),
                new Brand("JBL"),
                new Brand("Jbn"),
                new Brand("JBR WOOD"),
                new Brand("JDK"),
                new Brand("Jean Paul"),
                new Brand("Jedia"),
                new Brand("Jedson Guitars"),
                new Brand("Jeff Gold Graphics"),
                new Brand("Jeff Rowland"),
                new Brand("Jeffrey David"),
                new Brand("Jellifish"),
                new Brand("Jen"),
                new Brand("Jensen"),
                new Brand("Jerry Jones Guitars"),
                new Brand("Jerzy Drozd"),
                new Brand("Jess Loureiro"),
                new Brand("Jet 2000"),
                new Brand("Jet City Amplification"),
                new Brand("Jet Tone"),
                new Brand("JetSlide"),
                new Brand("Jetter"),
                new Brand("JHS Pedals"),
                new Brand("Jiggs"),
                new Brand("Jim Dunlop"),
                new Brand("Jim Harley"),
                new Brand("Jim Redgate Guitars"),
                new Brand("Jim Reed"),
                new Brand("Jimi Hendrix"),
                new Brand("JJ Electronics"),
                new Brand("JJ Guitars"),
                new Brand("JJ Scott"),
                new Brand("JK Audio"),
                new Brand("JL Cooper"),
                new Brand("JLH Technologies"),
                new Brand("Jm Forest"),
                new Brand("Jmi"),
                new Brand("JMLab"),
                new Brand("Jo Ral"),
                new Brand("Joan Cashimira"),
                new Brand("Jocavi"),
                new Brand("Jodavi"),
                new Brand("Jodi Head"),
                new Brand("Jody Jazz"),
                new Brand("Joe Barden"),
                new Brand("Joe Montineri Custom Drums"),
                new Brand("Joemeek"),
                new Brand("Johann Bruck"),
                new Brand("Johannes Gerber"),
                new Brand("Johannus Organs"),
                new Brand("John Brinsmead &amp; Sons"),
                new Brand("John Hornby Skewes"),
                new Brand("John Packner"),
                new Brand("John Pearse"),
                new Brand("Johnson"),
                new Brand("Jolana Guitars"),
                new Brand("Jolida"),
                new Brand("Jollysun"),
                new Brand("Jomox"),
                new Brand("José Lopez Bellido"),
                new Brand("Jose Ramirez"),
                new Brand("Jose Torres"),
                new Brand("Josef Lazar"),
                new Brand("Joseph Klotz"),
                new Brand("JOSEPHSON"),
                new Brand("JOTLER CUSTOM GUITARS"),
                new Brand("Joyful Noise Drum"),
                new Brand("Joyo"),
                new Brand("JTS"),
                new Brand("Juan Estruch"),
                new Brand("Juan Hernandez"),
                new Brand("Juan Martinez"),
                new Brand("Jubal"),
                new Brand("Juice Goose"),
                new Brand("Jupiter"),
                new Brand("JustEnough"),
                new Brand("Jvc"),
                new Brand("JZ Microphones"),
                new Brand("K&amp;H Kühnl &amp; Hoyer"),
                new Brand("K&amp;K Sound"),
                new Brand("K&amp;M"),
                new Brand("Kable Keepers"),
                new Brand("Kaces"),
                new Brand("Kafko"),
                new Brand("Kahler"),
                new Brand("Kala Ukulele"),
                new Brand("Kalison"),
                new Brand("Kalmann Piano"),
                new Brand("KAM"),
                new Brand("Kamaka"),
                new Brand("Kangaba"),
                new Brand("Kanile''a"),
                new Brand("Kanstul"),
                new Brand("Kaotica"),
                new Brand("Kappler Coblenz"),
                new Brand("Karathon"),
                new Brand("Karl Glaser"),
                new Brand("Karma"),
                new Brand("K-array"),
                new Brand("Kashian"),
                new Brand("Kastner Pianos"),
                new Brand("Kasuga"),
                new Brand("KAT Percussion"),
                new Brand("Katho"),
                new Brand("Kawai"),
                new Brand("Kay"),
                new Brand("Keeler Designs"),
                new Brand("Keeley"),
                new Brand("Kef"),
                new Brand("Keilwerth"),
                new Brand("Keiper Guitars"),
                new Brand("Keith McMillen"),
                new Brand("Keller"),
                new Brand("Kellermann"),
                new Brand("Kelly"),
                new Brand("Kemble"),
                new Brand("Kemp Elektroniks"),
                new Brand("Kemper"),
                new Brand("Kempton"),
                new Brand("Ken Rose"),
                new Brand("Ken Smith"),
                new Brand("Kendrick"),
                new Brand("Kensington"),
                new Brand("Kent Armstrong Pickups"),
                new Brand("Kenton"),
                new Brand("Kentucky"),
                new Brand("Kenwood"),
                new Brand("Kenyon"),
                new Brand("Kepur"),
                new Brand("Kerly"),
                new Brand("Kessel Pianos"),
                new Brand("Ketron"),
                new Brand("Keyb Organ"),
                new Brand("Keyhelm"),
                new Brand("Keywear"),
                new Brand("Khaler"),
                new Brand("Khan Audio"),
                new Brand("KickPort"),
                new Brand("Kidsplay"),
                new Brand("Kiesel"),
                new Brand("Kilpatrick Audio"),
                new Brand("Kimaxe"),
                new Brand("Kimball"),
                new Brand("Kimbo"),
                new Brand("Kind Audio"),
                new Brand("Kinetik"),
                new Brand("King"),
                new Brand("King Capitol Punishment"),
                new Brand("King David"),
                new Brand("King Doublebass"),
                new Brand("KING TONE GUITAR"),
                new Brand("King''s Stone"),
                new Brand("Kingsley Amplifiers"),
                new Brand("Kingston"),
                new Brand("Kinman"),
                new Brand("Kinsman"),
                new Brand("Kirchhoff Schlagwerk"),
                new Brand("Kismet"),
                new Brand("Kiso Suzuki"),
                new Brand("kiStation"),
                new Brand("Kitty Hawk"),
                new Brand("Klark Teknik"),
                new Brand("KLD"),
                new Brand("Klein &amp; Hummel"),
                new Brand("Klein Guitars"),
                new Brand("Klein Pickups"),
                new Brand("Klemt Echolette"),
                new Brand("K-Line Guitars"),
                new Brand("Kling &amp; Freitag"),
                new Brand("Klingmann"),
                new Brand("Klipsch"),
                new Brand("Klira"),
                new Brand("Klon"),
                new Brand("Klotz"),
                new Brand("Kluson"),
                new Brand("KMD"),
                new Brand("Kme"),
                new Brand("Knabe Pianos"),
                new Brand("Knaggs Guitars"),
                new Brand("Knas"),
                new Brand("Knosti"),
                new Brand("Koala Music"),
                new Brand("Kobble"),
                new Brand("Koch"),
                new Brand("Kodak"),
                new Brand("Kohlert"),
                new Brand("Kohno Guitars"),
                new Brand("Kolberg"),
                new Brand("KOMA Elektronik"),
                new Brand("Komet"),
                new Brand("Konig"),
                new Brand("Konig &amp; Meyer"),
                new Brand("Kontrol Dj"),
                new Brand("Kooiman"),
                new Brand("Kool Light"),
                new Brand("Koolsound"),
                new Brand("KOR Pedals"),
                new Brand("Korala"),
                new Brand("Korg"),
                new Brand("Kornbherg"),
                new Brand("Koss"),
                new Brand("Kosth"),
                new Brand("Kotato &amp; Fukushima"),
                new Brand("Kraken Guitars"),
                new Brand("Kramer"),
                new Brand("Krank"),
                new Brand("Krank Amplification"),
                new Brand("Kratt"),
                new Brand("Krauss"),
                new Brand("Krell"),
                new Brand("Kremona"),
                new Brand("Krest Cymbals"),
                new Brand("KRK"),
                new Brand("Kronbauer"),
                new Brand("Krundaal"),
                new Brand("KS Audio"),
                new Brand("KSD"),
                new Brand("KSdigital"),
                new Brand("KSP"),
                new Brand("KTS Titanium"),
                new Brand("Kubicki"),
                new Brand("Kultur"),
                new Brand("Kumika"),
                new Brand("Kun"),
                new Brand("Kurzweil"),
                new Brand("Kush Audio"),
                new Brand("Kustom"),
                new Brand("KV2 Audio"),
                new Brand("Kvant"),
                new Brand("Kydd"),
                new Brand("Kyser"),
                new Brand("L.A. Sax"),
                new Brand("L.POLVERINI 1889"),
                new Brand("L.R. Baggs"),
                new Brand("La Audio"),
                new Brand("La Bella"),
                new Brand("La Mancha Guitars"),
                new Brand("La Patrie"),
                new Brand("LAA Custom"),
                new Brand("LaB di Lucio Bazzocchi"),
                new Brand("Lab Gruppen"),
                new Brand("Lab.gruppen"),
                new Brand("LaBella"),
                new Brand("Laberte-Humbert"),
                new Brand("Laboga"),
                new Brand("Lace"),
                new Brand("LaCie"),
                new Brand("L-Acoustics"),
                new Brand("Lafin"),
                new Brand("LAG Guitars"),
                new Brand("Laguna"),
                new Brand("Lake people"),
                new Brand("Lakewood"),
                new Brand("Lakland"),
                new Brand("Lama"),
                new Brand("Lamberson"),
                new Brand("Lamp Lite"),
                new Brand("Lampcraft"),
                new Brand("Lampo"),
                new Brand("Lan Audio"),
                new Brand("Landgraff"),
                new Brand("Landing Bass"),
                new Brand("Landola"),
                new Brand("Laney"),
                new Brand("Lang Amplification"),
                new Brand("Lange"),
                new Brand("Langevin"),
                new Brand("Langner"),
                new Brand("Lanikai"),
                new Brand("Lantec"),
                new Brand("Lap axe"),
                new Brand("Lark"),
                new Brand("Larrivèe"),
                new Brand("L''Artigiana"),
                new Brand("Laserworld"),
                new Brand("Laskey"),
                new Brand("Latch Lake"),
                new Brand("Latin Benson"),
                new Brand("Latin Percussion"),
                new Brand("Laurus"),
                new Brand("Lauten Audio"),
                new Brand("Lava"),
                new Brand("LaVoz"),
                new Brand("Lavry Engineering"),
                new Brand("Lawton"),
                new Brand("Lax"),
                new Brand("Layolo"),
                new Brand("Lazeman"),
                new Brand("Lazy J Projects"),
                new Brand("LD Systems"),
                new Brand("Le Soprano"),
                new Brand("Leach Guitars"),
                new Brand("Leap Motion"),
                new Brand("Lebayle"),
                new Brand("LeBlanc"),
                new Brand("Leblanc by Backun"),
                new Brand("Lechner"),
                new Brand("Lectrosonics"),
                new Brand("LedLux"),
                new Brand("Ledwall Star"),
                new Brand("Lee Jackson"),
                new Brand("Lee Oskar"),
                new Brand("Leedy Drums"),
                new Brand("Leem"),
                new Brand("Lefima"),
                new Brand("Legator"),
                new Brand("Legend Guitars"),
                new Brand("Légère"),
                new Brand("Legg Guitars"),
                new Brand("Lehle"),
                new Brand("Leho Ukuleles"),
                new Brand("LEM"),
                new Brand("Lenco"),
                new Brand("Lengardo"),
                new Brand("Lenzner"),
                new Brand("Leo Quan"),
                new Brand("LepLoop"),
                new Brand("Leslie"),
                new Brand("Levin Guitars"),
                new Brand("Levinson"),
                new Brand("Levy''s"),
                new Brand("Lewitt"),
                new Brand("Lexicon"),
                new Brand("Lexonpro"),
                new Brand("Lien Cheng"),
                new Brand("Life"),
                new Brand("Lifetime"),
                new Brand("Light Planet"),
                new Brand("Lightfoot Labs"),
                new Brand("Lighting"),
                new Brand("Lightmaxx"),
                new Brand("LightSnake"),
                new Brand("LightWave"),
                new Brand("Limec"),
                new Brand("Lindell Audio"),
                new Brand("Linden"),
                new Brand("Lindert"),
                new Brand("Lindo"),
                new Brand("Lindy"),
                new Brand("Lindy Fralin"),
                new Brand("Line 6"),
                new Brand("Line Audio"),
                new Brand("Line for Stage"),
                new Brand("Line Parts"),
                new Brand("Line6"),
                new Brand("LINFAUDIO"),
                new Brand("Link Italy"),
                new Brand("Linko"),
                new Brand("Litec"),
                new Brand("Litecraft"),
                new Brand("Lite-Puter"),
                new Brand("Litestructures"),
                new Brand("Little Labs"),
                new Brand("littlepapercones"),
                new Brand("Littlite"),
                new Brand("Liutart e Tube Art"),
                new Brand("Liuteria Canova"),
                new Brand("Liuteria Cesarini"),
                new Brand("Liuteria Guarnieri"),
                new Brand("Liuteria Zacchetti"),
                new Brand("Liutus"),
                new Brand("Live Wire"),
                new Brand("Live Wire Solutions"),
                new Brand("Livewire Electronics"),
                new Brand("Livid Instruments"),
                new Brand("Lizard Spit"),
                new Brand("LM Products"),
                new Brand("LMI"),
                new Brand("Loco Box"),
                new Brand("Locto"),
                new Brand("Lodi Guitars"),
                new Brand("Logan"),
                new Brand("Logic Keyboard"),
                new Brand("Logidy"),
                new Brand("Logjam Music"),
                new Brand("Lollar Pickups"),
                new Brand("Lombardi"),
                new Brand("London City"),
                new Brand("Longhin Ampli"),
                new Brand("Loop-Master"),
                new Brand("Looptrotter"),
                new Brand("Lotus"),
                new Brand("Lotus Pedal"),
                new Brand("Loud Guitars"),
                new Brand("Loud Professional"),
                new Brand("Louis Electric Amplifier"),
                new Brand("Louis Renner"),
                new Brand("Lovadina"),
                new Brand("Lovatone"),
                new Brand("Lovepedal"),
                new Brand("Loveri Usa"),
                new Brand("Lovetone"),
                new Brand("Lowden"),
                new Brand("Loxx"),
                new Brand("LR Baggs"),
                new Brand("LR Soundproof"),
                new Brand("LsL Instruments"),
                new Brand("Lss"),
                new Brand("LT Sound"),
                new Brand("Ltd"),
                new Brand("Lubrostage"),
                new Brand("Lucchini"),
                new Brand("Lucero"),
                new Brand("Lucid"),
                new Brand("Lucida"),
                new Brand("Lucien"),
                new Brand("Ludwig"),
                new Brand("Luis Romero"),
                new Brand("Luke &amp; Daniel"),
                new Brand("Lumineze"),
                new Brand("Lumpy''s Tone Shop"),
                new Brand("Luna"),
                new Brand("Lunastone"),
                new Brand("Lundgren Pickups"),
                new Brand("Lupifaro"),
                new Brand("Lute Hole"),
                new Brand("Luthiers"),
                new Brand("Luxman"),
                new Brand("Luyben"),
                new Brand("Lynx Studio Technology"),
                new Brand("Lyon By Washburn"),
                new Brand("M Audio"),
                new Brand("M Capitale"),
                new Brand("M Live"),
                new Brand("M&amp;G Saxophones"),
                new Brand("M.J. Douglas"),
                new Brand("M@F"),
                new Brand("M3 Emthree"),
                new Brand("MA Lighting"),
                new Brand("Maag Audio"),
                new Brand("Mac Audio"),
                new Brand("Mack"),
                new Brand("Mackie"),
                new Brand("Mad Corporation"),
                new Brand("Mad Distribution"),
                new Brand("Mad Hatter Stompboxes"),
                new Brand("Mad Professor"),
                new Brand("Madamp"),
                new Brand("MadCat"),
                new Brand("Madison Amps"),
                new Brand("Madrigal Guitars"),
                new Brand("Maeari"),
                new Brand("Maestro"),
                new Brand("Magic Fluke"),
                new Brand("Magic Fx"),
                new Brand("Magix"),
                new Brand("Magma"),
                new Brand("Magnamusic"),
                new Brand("Magnat"),
                new Brand("Magnatone"),
                new Brand("Magnetic Effects"),
                new Brand("Magnetics"),
                new Brand("Magneto Audio Devices"),
                new Brand("Magnum"),
                new Brand("Magnum Pedal Steel"),
                new Brand("Magrabò"),
                new Brand("Mahaffay Amps"),
                new Brand("Mahalo"),
                new Brand("Mahi Mahi"),
                new Brand("Mahilele"),
                new Brand("Mahillon"),
                new Brand("Mahimahi"),
                new Brand("Mahler"),
                new Brand("Maino e Orsi"),
                new Brand("Maison"),
                new Brand("Majestic"),
                new Brand("Majid DRUMS"),
                new Brand("Majik Box"),
                new Brand("Majones"),
                new Brand("Makala"),
                new Brand("Makassar"),
                new Brand("Make Music"),
                new Brand("Make Noise"),
                new Brand("MakeMusic!"),
                new Brand("Malekko"),
                new Brand("Malletech"),
                new Brand("MalletKAT"),
                new Brand("Malone"),
                new Brand("Mam"),
                new Brand("Mama Pickups"),
                new Brand("Mancke"),
                new Brand("Manfrotto"),
                new Brand("Manhasset"),
                new Brand("Manhattan Analog"),
                new Brand("Manikin Electronic"),
                new Brand("Manley"),
                new Brand("Manlius Pickups"),
                new Brand("Manne"),
                new Brand("Manne Design"),
                new Brand("MannMade USA"),
                new Brand("Mann''s"),
                new Brand("Manson Guitars"),
                new Brand("Mantini Guitarras"),
                new Brand("Mantra"),
                new Brand("Manuel Rodriguez"),
                new Brand("Mapa"),
                new Brand("Mapex"),
                new Brand("Maple Drum"),
                new Brand("Maranatha! Music"),
                new Brand("Marantz"),
                new Brand("Maratea Custom Audio"),
                new Brand("Marca Reeds"),
                new Brand("Marchesini Chitarre"),
                new Brand("Marchi"),
                new Brand("Marcinkiewicz Mouthpieces"),
                new Brand("Marcus Bonna"),
                new Brand("Mari"),
                new Brand("Marigaux"),
                new Brand("Mario Corso"),
                new Brand("Mario Garrone"),
                new Brand("Mario Grimaldi"),
                new Brand("Mark Foley"),
                new Brand("Mark Levinson"),
                new Brand("Mark of the Unicorn (MOTU)"),
                new Brand("MarkAudio"),
                new Brand("Markbass"),
                new Brand("MarkDrum"),
                new Brand("MarkOne Audio"),
                new Brand("Marks"),
                new Brand("Marleaux"),
                new Brand("Marma"),
                new Brand("Marshall"),
                new Brand("Marshall Electronics"),
                new Brand("Martin"),
                new Brand("Martin &amp; Co."),
                new Brand("Martin Audio"),
                new Brand("Martin LeBlanc"),
                new Brand("Martinez Guitars.com"),
                new Brand("Maruni"),
                new Brand("Maruszczyk Instruments"),
                new Brand("Marvel"),
                new Brand("Marvin"),
                new Brand("Marvit"),
                new Brand("Masaaki"),
                new Brand("Masaki Sakurai"),
                new Brand("Masaru Kohno"),
                new Brand("Maselec"),
                new Brand("Masetti Liuteria"),
                new Brand("Masi"),
                new Brand("Mason &amp; Hamlin"),
                new Brand("Masotti Guitar Devices"),
                new Brand("MassBass"),
                new Brand("Massoni"),
                new Brand("Master &amp; Dynamic"),
                new Brand("Master Audio"),
                new Brand("Masterwork"),
                new Brand("Masterwriter"),
                new Brand("Mastery"),
                new Brand("Mastro Valvola"),
                new Brand("MatAmp"),
                new Brand("Matchless"),
                new Brand("Mateki Flute"),
                new Brand("Maton Guitars"),
                new Brand("Matrix"),
                new Brand("MATT BETTIS"),
                new Brand("Mattia Cigalini"),
                new Brand("Mattia Franchin guitars"),
                new Brand("M-Audio"),
                new Brand("Mauro Freschi Guitars"),
                new Brand("Maverick Guitars"),
                new Brand("Mavis"),
                new Brand("Maxell"),
                new Brand("Maxine Guitars"),
                new Brand("Maxon"),
                new Brand("Maxtone"),
                new Brand("Maya Guitars"),
                new Brand("Maybach"),
                new Brand("Mayones"),
                new Brand("Mayson Guitars"),
                new Brand("MB Quart"),
                new Brand("MBL"),
                new Brand("M-Blaster"),
                new Brand("MBT"),
                new Brand("MC Audio"),
                new Brand("Mc Crypt"),
                new Brand("MC Drums"),
                new Brand("Mc Nash"),
                new Brand("MC2 Audio"),
                new Brand("McAlister"),
                new Brand("McAntony Guitars"),
                new Brand("MCAudioLab"),
                new Brand("McDSP"),
                new Brand("McFarlow"),
                new Brand("McIlroy Guitars"),
                new Brand("McIntosh"),
                new Brand("McLore"),
                new Brand("McNally"),
                new Brand("McVoice"),
                new Brand("MD Musical Accessories"),
                new Brand("MDF"),
                new Brand("Mdlr Case"),
                new Brand("Me All"),
                new Brand("Me all Light"),
                new Brand("Me all Sound"),
                new Brand("Meazzi"),
                new Brand("Mec-pickups"),
                new Brand("Medeli"),
                new Brand("Mediapresse"),
                new Brand("Meeblip"),
                new Brand("Mega Amp"),
                new Brand("MegaDrum"),
                new Brand("Megatar"),
                new Brand("Megatone"),
                new Brand("Mei Mei"),
                new Brand("Meìnel"),
                new Brand("Meinl"),
                new Brand("Meinl Weston"),
                new Brand("Meisel"),
                new Brand("Meisterklasse"),
                new Brand("Mel Bay"),
                new Brand("Melancon Guitars"),
                new Brand("Melford"),
                new Brand("Mellotron"),
                new Brand("Mellowtone"),
                new Brand("Melody Guitars"),
                new Brand("Melody Major"),
                new Brand("Melton"),
                new Brand("Memorex"),
                new Brand("Menatone"),
                new Brand("Mengascini"),
                new Brand("Mengozzi"),
                new Brand("Mennekes"),
                new Brand("Mensinger Guitars"),
                new Brand("Mercury Drum"),
                new Brand("Mercury Magnetics"),
                new Brand("Mercury Recording Equipment"),
                new Brand("Meredith Music"),
                new Brand("Merging Technologies"),
                new Brand("Merida"),
                new Brand("Meridian Audio"),
                new Brand("Meridian Guitars"),
                new Brand("meris"),
                new Brand("Merrill Guitars"),
                new Brand("Mesa Boogie"),
                new Brand("Metaltronix"),
                new Brand("Metasonix"),
                new Brand("Metelli Guitars"),
                new Brand("Meteoro"),
                new Brand("Metric Halo"),
                new Brand("Metrophones"),
                new Brand("Meyer"),
                new Brand("Meyer Sound"),
                new Brand("Mezzabarba"),
                new Brand("MFB"),
                new Brand("MG"),
                new Brand("MI Audio"),
                new Brand("Michael Kelly"),
                new Brand("Michael Messer Resonator Guitar"),
                new Brand("Micro"),
                new Brand("MicroBoards"),
                new Brand("Microdesignum"),
                new Brand("Micromega"),
                new Brand("Micronet"),
                new Brand("Microsonic Music"),
                new Brand("Microtech Gefell"),
                new Brand("Microtips"),
                new Brand("Midas"),
                new Brand("Middle Atlantic"),
                new Brand("Mid-Fi Electronics"),
                new Brand("MIDI Solutions"),
                new Brand("Midiman"),
                new Brand("Midione"),
                new Brand("Midiplus"),
                new Brand("Miditech"),
                new Brand("Miditemp"),
                new Brand("Mighty Bright"),
                new Brand("Mighty Mite"),
                new Brand("Miguel Almería"),
                new Brand("Miguel Angel"),
                new Brand("Miguel Demarias"),
                new Brand("Miguel Di Carlo"),
                new Brand("Mike Balter"),
                new Brand("Mike Caddy"),
                new Brand("Mike Lull"),
                new Brand("Mikrofon-M"),
                new Brand("Miktek Audio"),
                new Brand("Milab"),
                new Brand("Millenium"),
                new Brand("Millenium Drums"),
                new Brand("Millennia"),
                new Brand("Miller"),
                new Brand("Miller Freeman"),
                new Brand("Milos"),
                new Brand("Minarik"),
                new Brand("Mindprint"),
                new Brand("MindSound"),
                new Brand("Minotaur Sonic Terrors"),
                new Brand("Mipro"),
                new Brand("Mirage"),
                new Brand("Miraphone"),
                new Brand("MirrorPix"),
                new Brand("Mi-Si Electronics"),
                new Brand("Mission Engineering"),
                new Brand("Mitchell"),
                new Brand("Mitchell Lurie"),
                new Brand("Mitec"),
                new Brand("Mito"),
                new Brand("Mitsubishi"),
                new Brand("Mixars"),
                new Brand("MixBooks"),
                new Brand("Mixta Music"),
                new Brand("MixVibes"),
                new Brand("Miyazawa"),
                new Brand("MJM Guitar FX"),
                new Brand("MJS"),
                new Brand("MJT"),
                new Brand("MK Contrabbassi Elettrici"),
                new Brand("Mkc"),
                new Brand("MKM")


        );
    }
}
