package com.giga.museek.bootstrap;

import com.giga.museek.documents.Brand;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class BrandLists4 {
    private  List<Brand> brands;
    public BrandLists4() {
        brands = fillAllBrands1();

    }

    private List<Brand> fillAllBrands1() {

        return List.of(

                new Brand("MKS Professional"),
                new Brand("MMP Brasswind"),
                new Brand("Mnk"),
                new Brand("Mobil Truss"),
                new Brand("Modal Electronics"),
                new Brand("Modartt"),
                new Brand("Modcan Synthesizer"),
                new Brand("Mode Machines"),
                new Brand("Modern Drummer"),
                new Brand("Modtone"),
                new Brand("Modulus"),
                new Brand("Moeck"),
                new Brand("Moen Pedals"),
                new Brand("Moffa Guitars"),
                new Brand("Mogami"),
                new Brand("Mogar"),
                new Brand("Mogees"),
                new Brand("Mojave Audio"),
                new Brand("Mojo Hand"),
                new Brand("Mojotone"),
                new Brand("Moldovan Amp"),
                new Brand("Molinelli"),
                new Brand("Mollard"),
                new Brand("Mollenhauer"),
                new Brand("Molpass"),
                new Brand("Molten Voltage"),
                new Brand("Monacor"),
                new Brand("Monarch"),
                new Brand("Monette"),
                new Brand("Monitor Audio"),
                new Brand("Monkey Banana"),
                new Brand("Mono Case"),
                new Brand("Monolith"),
                new Brand("Moid"),
                new Brand("Monster"),
                new Brand("Monster Audio"),
                new Brand("Monster Cable"),
                new Brand("Monster Effect"),
                new Brand("Monster Power"),
                new Brand("Monster Relic"),
                new Brand("Montani"),
                new Brand("Montarbo"),
                new Brand("Monte Allums"),
                new Brand("Montreux"),
                new Brand("Monzino"),
                new Brand("Moody"),
                new Brand("Mooer"),
                new Brand("Moog"),
                new Brand("Moog Music"),
                new Brand("Moollon"),
                new Brand("Moon Guitars"),
                new Brand("Moonphaser"),
                new Brand("Mordaunt-Short"),
                new Brand("Moreno"),
                new Brand("Moreschi"),
                new Brand("Morgan"),
                new Brand("Morgan Guitars"),
                new Brand("Morgan Monroe"),
                new Brand("Morgancase"),
                new Brand("Morley"),
                new Brand("Morpheus"),
                new Brand("Morrell"),
                new Brand("Morris"),
                new Brand("Moses"),
                new Brand("Mosky"),
                new Brand("Mosrite Guitars"),
                new Brand("Mossman"),
                new Brand("Motion Sound"),
                new Brand("Motu"),
                new Brand("Mountainking Electronics"),
                new Brand("Mouthpiece Café"),
                new Brand("Movall"),
                new Brand("Mozzani Liuteria"),
                new Brand("Mp Audio"),
                new Brand("MP Guitars"),
                new Brand("MP Pickups"),
                new Brand("Mpe"),
                new Brand("MPE Audio"),
                new Brand("MPGear"),
                new Brand("MPM"),
                new Brand("M-Pro"),
                new Brand("Mr. b Music Family"),
                new Brand("Mr. Black Pedals"),
                new Brand("MS Sound Project"),
                new Brand("MSI"),
                new Brand("MTD"),
                new Brand("MTV Books"),
                new Brand("Mullard"),
                new Brand("Müller-Schiedmayer"),
                new Brand("Multivox"),
                new Brand("Muramatsu"),
                new Brand("Murat Diril"),
                new Brand("Musa Drums"),
                new Brand("Musart"),
                new Brand("Muse Research"),
                new Brand("Musedo"),
                new Brand("Muses"),
                new Brand("Music Accessories"),
                new Brand("Music CD"),
                new Brand("Music Industry Products"),
                new Brand("Music Man"),
                new Brand("Music People"),
                new Brand("Music Sales"),
                new Brand("Musical Fidelity"),
                new Brand("Musician Sound Design"),
                new Brand("Musicians Gear"),
                new Brand("Musician''s Institute"),
                new Brand("Musicom Lab"),
                new Brand("MusiCover"),
                new Brand("Musicrew"),
                new Brand("Musictech"),
                new Brand("Musicvox"),
                new Brand("MusicXPC"),
                new Brand("Musikalia"),
                new Brand("Musikding"),
                new Brand("Musikraft"),
                new Brand("Musima"),
                new Brand("Musique Custom Guitars"),
                new Brand("Musitalia"),
                new Brand("Musitek"),
                new Brand("Musser"),
                new Brand("Mutable Instruments"),
                new Brand("Mutec"),
                new Brand("Mutron"),
                new Brand("Mutronics"),
                new Brand("Muza"),
                new Brand("MVP"),
                new Brand("mwm phase"),
                new Brand("MXL"),
                new Brand("MXR"),
                new Brand("My Audio"),
                new Brand("My Music"),
                new Brand("My Power"),
                new Brand("Mytek"),
                new Brand("N Tune"),
                new Brand("Nad"),
                new Brand("Nady"),
                new Brand("Nagahara Flutes"),
                new Brand("Nagra Audio"),
                new Brand("Nakamichi"),
                new Brand("Napalm Pedals"),
                new Brand("Nardelli"),
                new Brand("Nash"),
                new Brand("Nashville"),
                new Brand("Naska Belts"),
                new Brand("Natal"),
                new Brand("National"),
                new Brand("National Picks"),
                new Brand("Native Instruments"),
                new Brand("Navarro"),
                new Brand("Navini Fisarmoniche"),
                new Brand("NDS Music"),
                new Brand("NEA Music Inside"),
                new Brand("Neary"),
                new Brand("Nec"),
                new Brand("Nechville"),
                new Brand("Neewer"),
                new Brand("Nektar"),
                new Brand("Nemesis"),
                new Brand("Nemo Sound"),
                new Brand("Nemphasis"),
                new Brand("Neo Instruments"),
                new Brand("Neo Oyaide"),
                new Brand("Neotech"),
                new Brand("Neptune"),
                new Brand("NetworkSound"),
                new Brand("Neumann"),
                new Brand("Neumeyer Pianos"),
                new Brand("Neunaber Audio Effects"),
                new Brand("Neupert"),
                new Brand("Neuratron"),
                new Brand("Neuser Basses"),
                new Brand("Neutrik"),
                new Brand("Neve"),
                new Brand("New England Digital"),
                new Brand("New Old Sound Ltd"),
                new Brand("Newtone Strings"),
                new Brand("Nexo"),
                new Brand("Nick Page Guitars"),
                new Brand("Nickerson Guitars"),
                new Brand("Niedermeyer"),
                new Brand("Nieer"),
                new Brand("Night Angels Electronics"),
                new Brand("Nik Huber"),
                new Brand("Nikko"),
                new Brand("Ningbo"),
                new Brand("Nino"),
                new Brand("Nioi Design"),
                new Brand("NitroCab"),
                new Brand("Nobels"),
                new Brand("Noble &amp; Cooley"),
                new Brand("Noblet"),
                new Brand("NOC3 Effects"),
                new Brand("Noise Control Audio"),
                new Brand("Noise Engineering"),
                new Brand("Noisemaker Effects"),
                new Brand("Noiz"),
                new Brand("Noll Electronic"),
                new Brand("Nomad"),
                new Brand("Nomad Factory"),
                new Brand("Nord"),
                new Brand("Nordiska Pianos"),
                new Brand("Nordstrand"),
                new Brand("Norelco"),
                new Brand("Norlin"),
                new Brand("Norman Guitars"),
                new Brand("Normandy Guitars"),
                new Brand("Notation Technologies"),
                new Brand("Notion"),
                new Brand("Notion Music"),
                new Brand("Nouglian"),
                new Brand("Nouse"),
                new Brand("Nova"),
                new Brand("Novalight"),
                new Brand("Novation"),
                new Brand("Nowsonic"),
                new Brand("Noyse"),
                new Brand("NS Design"),
                new Brand("NSI"),
                new Brand("Ntp"),
                new Brand("N-Tune"),
                new Brand("Nubino"),
                new Brand("Numark"),
                new Brand("Nuova"),
                new Brand("Nuova Elettronica"),
                new Brand("Nuvo"),
                new Brand("NUX"),
                new Brand("NV Group"),
                new Brand("O Tray"),
                new Brand("O.C.D.P."),
                new Brand("O.M. Mönnich"),
                new Brand("Oak River"),
                new Brand("Oasis"),
                new Brand("Obedia"),
                new Brand("Oberheim"),
                new Brand("Oboes.Ch."),
                new Brand("Obrac"),
                new Brand("Ocheltree"),
                new Brand("Octon"),
                new Brand("Odd AEon"),
                new Brand("Oddfellow Effects"),
                new Brand("Odery"),
                new Brand("Odyssey"),
                new Brand("Off The Wall"),
                new Brand("Offberg"),
                new Brand("Offenbach"),
                new Brand("OH!FX"),
                new Brand("Ohana Ukuleles"),
                new Brand("Ohm"),
                new Brand("OKKO"),
                new Brand("Oktava"),
                new Brand("Old Blood Noise Endeavours"),
                new Brand("Olds"),
                new Brand("Oleg Products"),
                new Brand("OLP"),
                new Brand("Olveira"),
                new Brand("Olympia Guitars"),
                new Brand("Olympus"),
                new Brand("Om Laboratories"),
                new Brand("Omega"),
                new Brand("OmegaFx"),
                new Brand("Omnia Audio"),
                new Brand("OmniaLaser"),
                new Brand("Omnirax"),
                new Brand("OmniSistem"),
                new Brand("Omnitronic"),
                new Brand("On Stage"),
                new Brand("On Stage Stands"),
                new Brand("One Control"),
                new Brand("Onerr"),
                new Brand("Onkyo"),
                new Brand("OP Electronics"),
                new Brand("Opcode"),
                new Brand("Open Labs"),
                new Brand("Opera"),
                new Brand("Optima Strings"),
                new Brand("Option 5"),
                new Brand("Optoma"),
                new Brand("Oqan"),
                new Brand("OQUAN"),
                new Brand("Oram"),
                new Brand("Orange"),
                new Brand("Orange County Drums and Percussion"),
                new Brand("Orban"),
                new Brand("Orbitone"),
                new Brand("Oregon"),
                new Brand("Origin Effects"),
                new Brand("Original Case"),
                new Brand("Original Fake"),
                new Brand("Original Swab"),
                new Brand("Orion Cymbals"),
                new Brand("Orion Effekte"),
                new Brand("Orla"),
                new Brand("Orlando"),
                new Brand("Ormsby Guitars"),
                new Brand("Orpheus"),
                new Brand("Ortega"),
                new Brand("Ortofon"),
                new Brand("Orville"),
                new Brand("Oscar Schmidt"),
                new Brand("Oscar Teller"),
                new Brand("Osmannbrass"),
                new Brand("Osram"),
                new Brand("Otari"),
                new Brand("Ottavianelli"),
                new Brand("Otto Link"),
                new Brand("Otto Musica"),
                new Brand("Outline"),
                new Brand("Ouverture"),
                new Brand("Ovation"),
                new Brand("Overlord of Music"),
                new Brand("Overloud"),
                new Brand("Overseas Connection"),
                new Brand("Overstayer"),
                new Brand("Overtone Labs"),
                new Brand("OX4 Pickups"),
                new Brand("Oxford Synthesiser Company"),
                new Brand("Oxfuzz"),
                new Brand("OXO"),
                new Brand("Oyster"),
                new Brand("Ozark"),
                new Brand("P&amp;P Amplification"),
                new Brand("P. Brunner"),
                new Brand("P.Mauriat"),
                new Brand("Pace"),
                new Brand("Pacemaker"),
                new Brand("Pacific Drums"),
                new Brand("Pacific Drums by DW"),
                new Brand("Pacific Trends"),
                new Brand("Pack A Stand"),
                new Brand("Paco Castillo"),
                new Brand("Padovani"),
                new Brand("Paesold"),
                new Brand("Paganini"),
                new Brand("Paia"),
                new Brand("Paige"),
                new Brand("Paiste"),
                new Brand("Palatino"),
                new Brand("Palladio Acoustics"),
                new Brand("Palmer"),
                new Brand("Palomino"),
                new Brand("Panamax"),
                new Brand("Panart"),
                new Brand("Panasonic"),
                new Brand("pandaMidi"),
                new Brand("Pangolin"),
                new Brand("Panther"),
                new Brand("Paoletti"),
                new Brand("Paolo Soprani"),
                new Brand("Paradis"),
                new Brand("Paramount Guitars"),
                new Brand("Paraschos"),
                new Brand("Parasound"),
                new Brand("Parduba"),
                new Brand("Pari organs"),
                new Brand("Park Amplifiers"),
                new Brand("Parker"),
                new Brand("Parkson"),
                new Brand("Parkwood"),
                new Brand("Parrot"),
                new Brand("Parsek"),
                new Brand("Parts Planet"),
                new Brand("Partsland"),
                new Brand("PartyBag"),
                new Brand("Pasha"),
                new Brand("Paso Sistemi Audio"),
                new Brand("Patrick Eggle Guitars"),
                new Brand("P-Audio"),
                new Brand("Paul Cochrane"),
                new Brand("Paul Mc Bray Guitars"),
                new Brand("Paul Reed Smith"),
                new Brand("Paulino Bernabe"),
                new Brand("Paulino Bernabé"),
                new Brand("Paxman"),
                new Brand("PCDJ"),
                new Brand("Pdc"),
                new Brand("PDP- Pacific Drum and Percussion"),
                new Brand("Peace Drum"),
                new Brand("Peace Love Productions"),
                new Brand("Peak"),
                new Brand("Pearce"),
                new Brand("Pearl"),
                new Brand("Pearl Flutes"),
                new Brand("Pearl River"),
                new Brand("Peavey"),
                new Brand("Pedal Monsters"),
                new Brand("Pedal Pad"),
                new Brand("Pedal Space"),
                new Brand("PedalGear"),
                new Brand("PedalSnake"),
                new Brand("Pedaltank"),
                new Brand("Pedaltrain"),
                new Brand("PedalworX"),
                new Brand("Pedi"),
                new Brand("Pedler"),
                new Brand("Pedro de Miguel"),
                new Brand("Pedro Martinez"),
                new Brand("Pedro Morientes"),
                new Brand("Pedulla"),
                new Brand("Peecker Sound"),
                new Brand("Peeker Sound"),
                new Brand("Peerless"),
                new Brand("Pegna Theremins"),
                new Brand("Peluso"),
                new Brand("Pendulum Audio"),
                new Brand("Penguin Books"),
                new Brand("Pensa Guitar"),
                new Brand("Pentatonic"),
                new Brand("Perez"),
                new Brand("Performance Plus"),
                new Brand("Peroni"),
                new Brand("Perreaux"),
                new Brand("Perri''s"),
                new Brand("Perri''s Leathers"),
                new Brand("Pete Cornish"),
                new Brand("Peter Eaton"),
                new Brand("Peter Florance Pickups"),
                new Brand("Petersen Designs"),
                new Brand("Peterson"),
                new Brand("Petrof"),
                new Brand("Pettyjohn Electronics"),
                new Brand("Petz"),
                new Brand("Pfeiffer"),
                new Brand("PFL Technology"),
                new Brand("PFX"),
                new Brand("PG Music"),
                new Brand("PGW"),
                new Brand("Phaeton Trumpets"),
                new Brand("Phantom Guitars"),
                new Brand("Phase Linear"),
                new Brand("PHD"),
                new Brand("Phidrums"),
                new Brand("Phil Barone"),
                new Brand("Phil Jones Bass"),
                new Brand("Philips"),
                new Brand("Phil-Tone"),
                new Brand("Phiton Resonators"),
                new Brand("Phoenix Audio"),
                new Brand("Phonic"),
                new Brand("Phonika Drums"),
                new Brand("Phon-X"),
                new Brand("Piano Services"),
                new Brand("Piano Wizard"),
                new Brand("Pianosound"),
                new Brand("Piatanesi"),
                new Brand("Picato"),
                new Brand("Pick N Glider"),
                new Brand("Pickboy"),
                new Brand("Pickering"),
                new Brand("Pickguardian"),
                new Brand("Pickupmakers"),
                new Brand("Piermaria"),
                new Brand("Pigini"),
                new Brand("Pignose Amps"),
                new Brand("Pigtronix"),
                new Brand("PikCard USA"),
                new Brand("Pillinger"),
                new Brand("Pilosio"),
                new Brand("Pinstripe Pedals"),
                new Brand("Pintech"),
                new Brand("Pioneer"),
                new Brand("Pioneer DJ"),
                new Brand("Pipers'' Choice"),
                new Brand("Pirastro"),
                new Brand("Piretti Liuteria"),
                new Brand("Pittsburgh"),
                new Brand("Pizzoaa Cajon"),
                new Brand("PJ Drums &amp; Percussion"),
                new Brand("PKV pickups"),
                new Brand("Placid Audio"),
                new Brand("Planet Drum"),
                new Brand("Planet Waves"),
                new Brand("Plankton Electronics"),
                new Brand("Plantronics"),
                new Brand("Plastica Panaro"),
                new Brand("Platinum Samples"),
                new Brand("PL-Audio"),
                new Brand("Players"),
                new Brand("Pleyel"),
                new Brand("Ploytec"),
                new Brand("Plush"),
                new Brand("Pmc"),
                new Brand("PMsnare"),
                new Brand("Pokketmixer"),
                new Brand("Polk Audio"),
                new Brand("Polverini"),
                new Brand("Polytone Amplifiers"),
                new Brand("Pomarico"),
                new Brand("Pontillo"),
                new Brand("Ponzol"),
                new Brand("POPS"),
                new Brand("Pork Pie"),
                new Brand("Port City Amps"),
                new Brand("Positive Grid"),
                new Brand("Postal Monkey"),
                new Brand("Potvin Guitars"),
                new Brand("Powell Flutes"),
                new Brand("Power Acoustik"),
                new Brand("Power Dynamics"),
                new Brand("Powerbox Factory"),
                new Brand("Powersoft"),
                new Brand("PowerSquid"),
                new Brand("PPA"),
                new Brand("PPG"),
                new Brand("PR Lighting"),
                new Brand("Practice Tracks"),
                new Brand("Prelude"),
                new Brand("Premier"),
                new Brand("Prescription Electronics"),
                new Brand("Presley Flight Case"),
                new Brand("Presonus"),
                new Brand("Prestige"),
                new Brand("Prestini"),
                new Brand("Preston"),
                new Brand("Primacoustic"),
                new Brand("Primary Line"),
                new Brand("Primera Technology"),
                new Brand("Primero"),
                new Brand("Prism Sound"),
                new Brand("Privada"),
                new Brand("Privitera"),
                new Brand("Pro Audio"),
                new Brand("Pro Co"),
                new Brand("Pro Ject"),
                new Brand("Pro Mark"),
                new Brand("Pro Media"),
                new Brand("Pro Music Software"),
                new Brand("Pro Snake"),
                new Brand("Pro Tec"),
                new Brand("Pro Tone Pedals"),
                new Brand("Pro Tour"),
                new Brand("Proac"),
                new Brand("ProAudio Press"),
                new Brand("Probe"),
                new Brand("Procases"),
                new Brand("Proco"),
                new Brand("Prodigy"),
                new Brand("Prodipe"),
                new Brand("Proel"),
                new Brand("Proel Die Hard"),
                new Brand("Professional Sound Light"),
                new Brand("Profile"),
                new Brand("Progetti Sonori"),
                new Brand("Proietta"),
                new Brand("Project Lead"),
                new Brand("ProLights"),
                new Brand("ProLine"),
                new Brand("Prolyte"),
                new Brand("Prometeus Guitars"),
                new Brand("Pronomic"),
                new Brand("Prop It"),
                new Brand("Propellerhead"),
                new Brand("Pro-Show"),
                new Brand("Proson"),
                new Brand("ProStageGear"),
                new Brand("Protection Racket"),
                new Brand("Proton"),
                new Brand("Protos"),
                new Brand("Protruss"),
                new Brand("Providence"),
                new Brand("ProWaves"),
                new Brand("PRS Guitars"),
                new Brand("Prudencio Saez"),
                new Brand("PSC Professional Sound Corporation"),
                new Brand("Psk"),
                new Brand("PSL Italy"),
                new Brand("PSSO"),
                new Brand("pTrumpet"),
                new Brand("Publison"),
                new Brand("Puchner"),
                new Brand("Pulse"),
                new Brand("Puma"),
                new Brand("Punch Pedals"),
                new Brand("Pur Cajon"),
                new Brand("PureCussion"),
                new Brand("Puresound Percussion"),
                new Brand("Purple Audio"),
                new Brand("Pyle Audio"),
                new Brand("PyP-Bomb"),
                new Brand("PZ Amp"),
                new Brand("Q Parts"),
                new Brand("Q Up Arts"),
                new Brand("Q4audio"),
                new Brand("QSC"),
                new Brand("Q-tuner"),
                new Brand("Quad"),
                new Brand("Quagliardi"),
                new Brand("Quantegy"),
                new Brand("QuartzColor"),
                new Brand("Quasimidi"),
                new Brand("Qube Audio"),
                new Brand("Qu-Bit Electronix"),
                new Brand("Quested"),
                new Brand("Quik Lok"),
                new Brand("Quiklok"),
                new Brand("Quilter Laboratories"),
                new Brand("Qwik Time"),
                new Brand("Qwik Tune"),
                new Brand("Radial"),
                new Brand("Radikal Technologies"),
                new Brand("Raganato"),
                new Brand("Raimundo"),
                new Brand("Rain Recording"),
                new Brand("Rainger FX"),
                new Brand("Rainsong"),
                new Brand("Ralph Marlin"),
                new Brand("RAM Audio"),
                new Brand("Ramble FX"),
                new Brand("Ramirez"),
                new Brand("Rammerdrum"),
                new Brand("Ramon Garcia"),
                new Brand("Ramon Latino"),
                new Brand("Ramper"),
                new Brand("Rampone &amp; Cazzani"),
                new Brand("RAMSA"),
                new Brand("Randall"),
                new Brand("Rane"),
                new Brand("Rash Guitars"),
                new Brand("Rasha Professional"),
                new Brand("Raspagni"),
                new Brand("Rath Trombones"),
                new Brand("Raven"),
                new Brand("Raven Images"),
                new Brand("Raxxess"),
                new Brand("Ray Ramirez"),
                new Brand("RAYGUN FX"),
                new Brand("RCA"),
                new Brand("RCF"),
                new Brand("Rch"),
                new Brand("Real Traps"),
                new Brand("Real World"),
                new Brand("Realist Pickup"),
                new Brand("Rean"),
                new Brand("Re''An"),
                new Brand("Reani Guitars"),
                new Brand("Rebeats Publications"),
                new Brand("Rebel Amps"),
                new Brand("Reckhorn"),
                new Brand("Record Research"),
                new Brand("Recording King"),
                new Brand("Red Beat Audio"),
                new Brand("Red Lighting"),
                new Brand("Red Panda"),
                new Brand("Red Shadow"),
                new Brand("Red Sound"),
                new Brand("Red Witch"),
                new Brand("Redmatica"),
                new Brand("Redpipe"),
                new Brand("Redplate Amps"),
                new Brand("Redstuff Amps"),
                new Brand("Reeds Australia"),
                new Brand("Rees Harps"),
                new Brand("Reference"),
                new Brand("Regal"),
                new Brand("Regal Tip"),
                new Brand("Regent"),
                new Brand("Reghin"),
                new Brand("REH"),
                new Brand("Reinhardt Pedals"),
                new Brand("Reismann"),
                new Brand("RELIC STAR CUSTOM SHOP"),
                new Brand("Reloop"),
                new Brand("Remic"),
                new Brand("Remo"),
                new Brand("René Guénot Paris"),
                new Brand("Renkus Heinz"),
                new Brand("Renoise"),
                new Brand("Republic Guitars"),
                new Brand("Resident Audio"),
                new Brand("Resocap"),
                new Brand("Resonans"),
                new Brand("Retro Channel"),
                new Brand("Retro Instruments"),
                new Brand("Retro Revival"),
                new Brand("Retro-king Amps"),
                new Brand("Retroman Music"),
                new Brand("Retro-Sonic"),
                new Brand("Reunion Blues"),
                new Brand("Revac"),
                new Brand("Revelation Guitars"),
                new Brand("Reverend Guitars"),
                new Brand("Revolution Drum"),
                new Brand("Revolver Audio"),
                new Brand("Revox"),
                new Brand("REVV"),
                new Brand("Rexer"),
                new Brand("Reynolds"),
                new Brand("RFT"),
                new Brand("RFX"),
                new Brand("Rhino"),
                new Brand("Rhodes"),
                new Brand("Rhythm Band"),
                new Brand("Rhythm Tech"),
                new Brand("Rialto"),
                new Brand("Ribbecke"),
                new Brand("Ribera"),
                new Brand("Richard Cocco Strings"),
                new Brand("Richmond Guitars"),
                new Brand("Richmond Organization"),
                new Brand("Richter"),
                new Brand("Richwood"),
                new Brand("Rick Levy"),
                new Brand("Rick Turner"),
                new Brand("Rickenbacker"),
                new Brand("Rico"),
                new Brand("Rico Royal"),
                new Brand("Ricordi"),
                new Brand("Ridenour"),
                new Brand("Rieger Kloss"),
                new Brand("Riffault"),
                new Brand("Right On!"),
                new Brand("Righton Straps"),
                new Brand("Rigotti Reeds"),
                new Brand("Rigoutat"),
                new Brand("Ringway"),
                new Brand("Rio Grande"),
                new Brand("Ripamonti"),
                new Brand("Rippen"),
                new Brand("Risa"),
                new Brand("Rising Software"),
                new Brand("Ritmuller"),
                new Brand("Ritter"),
                new Brand("Ritter &amp; Son"),
                new Brand("Rittor Music"),
                new Brand("Rivera"),
                new Brand("Riverhead Guitars"),
                new Brand("RJM"),
                new Brand("RKS Guitars"),
                new Brand("Rlaky"),
                new Brand("RMC"),
                new Brand("RME"),
                new Brand("RMI"),
                new Brand("RMV"),
                new Brand("Road Rage Pro Gear"),
                new Brand("Road Ready"),
                new Brand("Road Runner"),
                new Brand("Roadcase"),
                new Brand("Roadinger"),
                new Brand("Roadster"),
                new Brand("Rob Allen"),
                new Brand("Rob Papen"),
                new Brand("Robe"),
                new Brand("Robert Morley &amp; Co"),
                new Brand("Robert Stather Finsbury Park"),
                new Brand("Roberto Lanaro"),
                new Brand("Robin Guitars"),
                new Brand("Roc N Soc"),
                new Brand("Roche Thomas"),
                new Brand("Rock Axe"),
                new Brand("Rock Band"),
                new Brand("Rock House"),
                new Brand("Rock Jimmies"),
                new Brand("Rock n Roller"),
                new Brand("Rock Steady"),
                new Brand("RockBag"),
                new Brand("RockBass by Warwick"),
                new Brand("Rockboard"),
                new Brand("Rockbox"),
                new Brand("Rockbox Effects"),
                new Brand("Rockbridge Guitar Company"),
                new Brand("RockCase by Warwick"),
                new Brand("Rocketfire Guitars"),
                new Brand("Rockett"),
                new Brand("Rockfield"),
                new Brand("Rockinger"),
                new Brand("Rockman"),
                new Brand("Rock''n roll Relics Guitars"),
                new Brand("Rock''nroll Relics"),
                new Brand("RockStand"),
                new Brand("RockStand by Warwick"),
                new Brand("Rocktek"),
                new Brand("Rocktile"),
                new Brand("Rocktron"),
                new Brand("Rocktuner By Warwick"),
                new Brand("Rockwood"),
                new Brand("Rocky Mountain Slides"),
                new Brand("RODE"),
                new Brand("Rode Microphones"),
                new Brand("Rodgers Organi"),
                new Brand("Rodriguez"),
                new Brand("Roeseler"),
                new Brand("Roger Linn Design"),
                new Brand("Roger Mayer"),
                new Brand("Roger Schult"),
                new Brand("Rogers"),
                new Brand("Rogue"),
                new Brand("Rohema"),
                new Brand("Rok Axe"),
                new Brand("Rok Sak"),
                new Brand("Roland"),
                new Brand("Roli"),
                new Brand("Roling''s"),
                new Brand("Roll"),
                new Brand("Roller"),
                new Brand("Rolls"),
                new Brand("Romance"),
                new Brand("Romano Burini"),
                new Brand("Romeo Orsi"),
                new Brand("Ronisch Pianos"),
                new Brand("Roost"),
                new Brand("Root Guitar Effects"),
                new Brand("Roscoe Guitars"),
                new Brand("Rose"),
                new Brand("Rosenbach"),
                new Brand("Rosendahl"),
                new Brand("Rosler"),
                new Brand("Ross"),
                new Brand("Ross Mallet"),
                new Brand("Ross System"),
                new Brand("Rotel"),
                new Brand("Roth &amp; Junius"),
                new Brand("Rothwell Audio Products"),
                new Brand("Rotodrum"),
                new Brand("Rotosound"),
                new Brand("Rounder"),
                new Brand("Rousseau"),
                new Brand("Rover Banjos"),
                new Brand("Rovner"),
                new Brand("Rowin"),
                new Brand("Roy Benson"),
                new Brand("Royal"),
                new Brand("Royal Standard"),
                new Brand("Royer Labs"),
                new Brand("Roytek"),
                new Brand("Rozini"),
                new Brand("Rozz"),
                new Brand("RPM Dynamics"),
                new Brand("RSP Technologies"),
                new Brand("RSQ"),
                new Brand("RTF Custom Case"),
                new Brand("RTOM"),
                new Brand("Rtw"),
                new Brand("Ruby Tubes"),
                new Brand("Rud Ibach Sohn"),
                new Brand("Rudolf Meinl"),
                new Brand("Rudy Muck"),
                new Brand("Ruff Grip"),
                new Brand("Ruff Rider"),
                new Brand("Rugginenti"),
                new Brand("Rulez Queen"),
                new Brand("Runner"),
                new Brand("Runyon"),
                new Brand("Ruokangas"),
                new Brand("Rupert Neve Designs"),
                new Brand("RV Drums"),
                new Brand("Rycote"),
                new Brand("Rydeen"),
                new Brand("Ryoji Matsuoka"),
                new Brand("S. Clary"),
                new Brand("S.E. Shires"),
                new Brand("Saba"),
                new Brand("Sabbadius Pedals"),
                new Brand("Sabian"),
                new Brand("Sabine"),
                new Brand("Sabra"),
                new Brand("Sabre Guitars"),
                new Brand("Sadowsky Guitars"),
                new Brand("SAE"),
                new Brand("Saga"),
                new Brand("Sagitter"),
                new Brand("Sailor Jerry Clothing"),
                new Brand("Saito"),
                new Brand("Sakae"),
                new Brand("Sakura"),
                new Brand("Saldaneri Guitars"),
                new Brand("Salmieri Drums"),
                new Brand("Salterio"),
                new Brand("Salto Percussioni"),
                new Brand("Saluda Cymbals"),
                new Brand("Salvador Cortez"),
                new Brand("Salvi Harps"),
                new Brand("Samba"),
                new Brand("Samick"),
                new Brand("Samko"),
                new Brand("Samson"),
                new Brand("Samsun Cymbals"),
                new Brand("Samsung"),
                new Brand("Sanchez"),
                new Brand("Sanchis Lopez"),
                new Brand("Sanctuary"),
                new Brand("Sandberg"),
                new Brand("Sanden"),
                new Brand("SanDisk"),
                new Brand("Sanken"),
                new Brand("Sankyo Flute"),
                new Brand("Sanox"),
                new Brand("Sansone Strings"),
                new Brand("Sansui"),
                new Brand("Santa Cruz Guitar Company"),
                new Brand("Santander"),
                new Brand("Santech"),
                new Brand("Santos Martinez"),
                new Brand("Sanyo"),
                new Brand("Saporetti e Capelli"),
                new Brand("Sauter Pianos"),
                new Brand("Savannah"),
                new Brand("Savarez"),
                new Brand("Savior"),
                new Brand("Saxscape"),
                new Brand("SAXXAS"),
                new Brand("Sbe"),
                new Brand("Scala Guitars Usa"),
                new Brand("Scandalli"),
                new Brand("Scanic"),
                new Brand("Scarbee"),
                new Brand("Scarlata"),
                new Brand("Scarli"),
                new Brand("Schaaf"),
                new Brand("Schack Guitars"),
                new Brand("Schagerl"),
                new Brand("Schaller"),
                new Brand("Schalloch"),
                new Brand("Schatten Design"),
                new Brand("Schecter"),
                new Brand("Schertler"),
                new Brand("Scherzer"),
                new Brand("Schiedmayer"),
                new Brand("Schiit"),
                new Brand("Schilke"),
                new Brand("Schiller"),
                new Brand("Schimmel"),
                new Brand("Schlagwerk"),
                new Brand("Schober Organ"),
                new Brand("Schoenhut"),
                new Brand("Schoeps"),
                new Brand("Scholze"),
                new Brand("Schon"),
                new Brand("Schott"),
                new Brand("Schreiber"),
                new Brand("Schroeder"),
                new Brand("Schulmann"),
                new Brand("Schulze Pollmann"),
                new Brand("Scorpion"),
                new Brand("Scott"),
                new Brand("Scratch Pad"),
                new Brand("ScreenStars"),
                new Brand("Scumback Speakers &amp; Cabinets"),
                new Brand("SD Curlee"),
                new Brand("Sd System"),
                new Brand("SE Electronics"),
                new Brand("Seagull"),
                new Brand("Seck"),
                new Brand("Second Floor Music"),
                new Brand("Secret Efx"),
                new Brand("Secrets of the Pros"),
                new Brand("Seelake"),
                new Brand("Sefour"),
                new Brand("Seiko"),
                new Brand("Seiler"),
                new Brand("Seiwin"),
                new Brand("Sekova Guitars"),
                new Brand("Selmer"),
                new Brand("Selmer Paris"),
                new Brand("Sem"),
                new Brand("Semprini"),
                new Brand("Sennheiser"),
                new Brand("Sequential Circuits"),
                new Brand("Sequerra"),
                new Brand("Sequoia Saxophones"),
                new Brand("Serenelli"),
                new Brand("Session"),
                new Brand("Settimio Soprani"),
                new Brand("Seventh Circle Audio"),
                new Brand("Seydel"),
                new Brand("Seydel Sohne"),
                new Brand("Seymour Duncan"),
                new Brand("SGC Nanyo"),
                new Brand("SGM"),
                new Brand("SGR by Schecter"),
                new Brand("Shadow"),
                new Brand("Shadow Hills Industries"),
                new Brand("Shannan"),
                new Brand("Shard-Star"),
                new Brand("Sharp Concepts"),
                new Brand("Shauvet")


        );
    }
}
