package com.giga.museek.bootstrap;

import com.giga.museek.documents.Brand;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class BrandLists5 {
    private  List<Brand> brands;
    public BrandLists5() {
        brands = fillAllBrands1();

    }

    private List<Brand> fillAllBrands1() {

        return List.of(
                new Brand("Sheptone"),
                new Brand("Shergold Guitars"),
                new Brand("Sherman Filterbank"),
                new Brand("Shertler"),
                new Brand("Sherwood"),
                new Brand("Shift Line"),
                new Brand("Shigeru Kawai"),
                new Brand("Shimano"),
                new Brand("Shimmel"),
                new Brand("Shine Drums"),
                new Brand("Shin-Ei"),
                new Brand("Shiner"),
                new Brand("Shinp"),
                new Brand("Shin''s Music"),
                new Brand("Shires"),
                new Brand("Shiva Audio Devices"),
                new Brand("Shoe Pedals"),
                new Brand("Shoeps Microphones"),
                new Brand("Shonner"),
                new Brand("Shortbassone"),
                new Brand("Show-Lite"),
                new Brand("Showster"),
                new Brand("Showtec"),
                new Brand("Showven"),
                new Brand("Shredneck"),
                new Brand("Shubb"),
                new Brand("Shubb Pearse"),
                new Brand("Shure"),
                new Brand("SIB Effects"),
                new Brand("Sibelius"),
                new Brand("SIC Instruments"),
                new Brand("Sica"),
                new Brand("Sidewinder"),
                new Brand("Siegmund"),
                new Brand("Siel"),
                new Brand("Siemens"),
                new Brand("Sienzo"),
                new Brand("Sierra Guitars"),
                new Brand("Sigma Guitars"),
                new Brand("Signal Flex"),
                new Brand("Signatures Network"),
                new Brand("Signex"),
                new Brand("Siheko"),
                new Brand("SILENTSYSTEM"),
                new Brand("Silver Acoustic"),
                new Brand("Silver Bullet"),
                new Brand("Silver Creek"),
                new Brand("Silver Fox"),
                new Brand("Silverblade"),
                new Brand("Silversound"),
                new Brand("Silverstein"),
                new Brand("Silvertone"),
                new Brand("Simetrix"),
                new Brand("Simmons"),
                new Brand("Simms Watts"),
                new Brand("Simon &amp; Patrick"),
                new Brand("Singing Machine"),
                new Brand("Singular Sound"),
                new Brand("Sinn7"),
                new Brand("Sintel"),
                new Brand("Sire"),
                new Brand("Sirus"),
                new Brand("SIT"),
                new Brand("Skatterbrane Pickups"),
                new Brand("SKB"),
                new Brand("Skervesen Guitars"),
                new Brand("Skreddy Pedals"),
                new Brand("Skrydstrup R&amp;D"),
                new Brand("SKT"),
                new Brand("Skull Strings"),
                new Brand("Skullcandy"),
                new Brand("Sky"),
                new Brand("Skychord"),
                new Brand("Skytec"),
                new Brand("SL"),
                new Brand("Slammer Guitars"),
                new Brand("SlapKlatz"),
                new Brand("Slappa"),
                new Brand("Slate Pro Audio"),
                new Brand("Sleishman Drums"),
                new Brand("Slick"),
                new Brand("Slide O Mix"),
                new Brand("Slider Straps"),
                new Brand("Slingerland"),
                new Brand("Slug Percussion"),
                new Brand("SM Pro Audio"),
                new Brand("Smart Research"),
                new Brand("Smashboards"),
                new Brand("SMG"),
                new Brand("SmithsonMartin"),
                new Brand("Sml Saxophones"),
                new Brand("Smokey"),
                new Brand("SMP"),
                new Brand("SMPro Audio"),
                new Brand("Sms Audio"),
                new Brand("SMT"),
                new Brand("Snark"),
                new Brand("Snarling Dogs"),
                new Brand("Snouse Electric"),
                new Brand("Sobbat"),
                new Brand("SofiaMari"),
                new Brand("Softone"),
                new Brand("Softube"),
                new Brand("Sojin Pianos"),
                new Brand("Sojing"),
                new Brand("Sol Republic"),
                new Brand("Sola Sound"),
                new Brand("Solar by Sabian"),
                new Brand("Solar Guitars"),
                new Brand("Soldano"),
                new Brand("Solec"),
                new Brand("Solid State Logic"),
                new Brand("Solidbody Store"),
                new Brand("Solidgoldfx"),
                new Brand("Solidstand"),
                new Brand("Solina"),
                new Brand("Soller &amp; Sivcak"),
                new Brand("SoloEtte"),
                new Brand("Soloway Guitars"),
                new Brand("Solton"),
                new Brand("Som D''ouro"),
                new Brand("Sommer"),
                new Brand("Sonata"),
                new Brand("Song Xpress"),
                new Brand("Sonic Core"),
                new Brand("Sonic Implants"),
                new Brand("Sonic Reality"),
                new Brand("Sonic Research"),
                new Brand("Sonicake"),
                new Brand("Sonifex"),
                new Brand("Sonik Capsules"),
                new Brand("Sonitus"),
                new Brand("SONiVOX"),
                new Brand("Sonnox"),
                new Brand("Sonny the Lutist"),
                new Brand("Sonola"),
                new Brand("Sonoma Wire Works"),
                new Brand("Sonoma Wireworks"),
                new Brand("Sonor"),
                new Brand("Sonora"),
                new Brand("Sonos"),
                new Brand("Sontronics"),
                new Brand("Sonus Faber"),
                new Brand("Sonus Pater"),
                new Brand("Sonus Pedals"),
                new Brand("Sonuus"),
                new Brand("Sony"),
                new Brand("Sopar"),
                new Brand("Soul of Sound"),
                new Brand("Soultone Cymbals"),
                new Brand("Sound City"),
                new Brand("Sound Devices"),
                new Brand("Sound Man"),
                new Brand("Sound Percussion"),
                new Brand("Sound Quest"),
                new Brand("Sound Sculpture"),
                new Brand("Sound Skulptor"),
                new Brand("Soundart"),
                new Brand("Soundbrenner"),
                new Brand("Soundcraft"),
                new Brand("Soundcraftsmen"),
                new Brand("Soundelux Microphones"),
                new Brand("Soundfield"),
                new Brand("Soundking"),
                new Brand("SoundLab"),
                new Brand("Sounds We Make"),
                new Brand("Soundsation"),
                new Brand("Soundsphere"),
                new Brand("SoundTech"),
                new Brand("Soundtoys"),
                new Brand("Soundtracs"),
                new Brand("Soundwear"),
                new Brand("Sourceaudio"),
                new Brand("South Park"),
                new Brand("Sovtek"),
                new Brand("Soyuz"),
                new Brand("Spaceman Effects"),
                new Brand("Spacetek"),
                new Brand("Spada Music"),
                new Brand("Spaethe"),
                new Brand("Spalt Instruments"),
                new Brand("Sparkular"),
                new Brand("Spaun"),
                new Brand("Speakeasy"),
                new Brand("Spear Guitars"),
                new Brand("Speck Electronics"),
                new Brand("Spector Basses"),
                new Brand("Spectraflex"),
                new Brand("Spectral Audio"),
                new Brand("Spectrasonics"),
                new Brand("Speedster"),
                new Brand("Spendor Audio Systems"),
                new Brand("Sperzel"),
                new Brand("Spf"),
                new Brand("Spin Doctor"),
                new Brand("Spizz"),
                new Brand("Spizzichino Cymbals"),
                new Brand("SPL"),
                new Brand("Splawn"),
                new Brand("Spotlight"),
                new Brand("Springer Guitars"),
                new Brand("Sputnik Modular"),
                new Brand("Squier"),
                new Brand("Squier by Fender"),
                new Brand("SR Technologies"),
                new Brand("SR Technology"),
                new Brand("SRS Light Design"),
                new Brand("Sshhmute"),
                new Brand("ST Audio"),
                new Brand("St. Blues"),
                new Brand("Staccato Drums"),
                new Brand("Stage Accompany"),
                new Brand("Stage Magic"),
                new Brand("Stage Ninja"),
                new Brand("Stage Rig"),
                new Brand("stageClix"),
                new Brand("Stageline"),
                new Brand("Stagetrix"),
                new Brand("Stagg"),
                new Brand("Stairville"),
                new Brand("Stam Audio"),
                new Brand("Standtastic"),
                new Brand("Stanford Guitars"),
                new Brand("Stanton"),
                new Brand("Stanton DJ"),
                new Brand("Stanzani"),
                new Brand("Star Licks"),
                new Brand("Starfield"),
                new Brand("Starfire Guitars"),
                new Brand("StarLights Professional Effects"),
                new Brand("Starr Labs"),
                new Brand("StarSun"),
                new Brand("Startec"),
                new Brand("Starway"),
                new Brand("Stash Picks"),
                new Brand("Status"),
                new Brand("Stax"),
                new Brand("Stealton"),
                new Brand("Steavens"),
                new Brand("Steck"),
                new Brand("Stedman"),
                new Brand("Steelphon"),
                new Brand("Stefy Line"),
                new Brand("Steinbach"),
                new Brand("Steinberg"),
                new Brand("Steinberger"),
                new Brand("Steiner"),
                new Brand("Steinmayer"),
                new Brand("Steinway &amp; Sons"),
                new Brand("Stella"),
                new Brand("Stentor"),
                new Brand("Stephallen Guitars"),
                new Brand("Stephanhauser"),
                new Brand("Stephens Design"),
                new Brand("Stephenson Amp"),
                new Brand("Steppodrum"),
                new Brand("Stereoping Music Devices"),
                new Brand("Sterisol"),
                new Brand("Sterling Audio"),
                new Brand("Sterling by Music Man"),
                new Brand("Sterling Modular"),
                new Brand("Stetsbar"),
                new Brand("Stewart Ellis"),
                new Brand("Stewart MacDonald"),
                new Brand("StewMac"),
                new Brand("Steyr"),
                new Brand("Stinger"),
                new Brand("Stocco Drums"),
                new Brand("Stocco Fisarmoniche"),
                new Brand("Stomp Under Foot"),
                new Brand("Stompamp"),
                new Brand("Stomvi"),
                new Brand("Stone Deaf FX"),
                new Brand("Stonecastle"),
                new Brand("Stonehenge Guitars"),
                new Brand("Storm"),
                new Brand("Stowasser"),
                new Brand("Straightwire"),
                new Brand("Strand Lighting"),
                new Brand("Strandberg Guitars"),
                new Brand("Strasser Marigaux SML"),
                new Brand("Stratos"),
                new Brand("Street Audio"),
                new Brand("Strike"),
                new Brand("String Letter"),
                new Brand("String Master"),
                new Brand("String Swing"),
                new Brand("StringTek"),
                new Brand("Stromberg Guitars"),
                new Brand("Strunal"),
                new Brand("Strymon"),
                new Brand("Stuart"),
                new Brand("Studer"),
                new Brand("Studio 49"),
                new Brand("Studio Due"),
                new Brand("Studio Electronics"),
                new Brand("Studio Projects"),
                new Brand("Studio RTA"),
                new Brand("Studiologic"),
                new Brand("Studiomaster"),
                new Brand("StudioPhile"),
                new Brand("Subdecay"),
                new Brand("Submersible Music"),
                new Brand("SubtleNoiseMaker"),
                new Brand("SubZero"),
                new Brand("Suhr Guitars"),
                new Brand("Summit Audio"),
                new Brand("Sumo Amps"),
                new Brand("Sundown"),
                new Brand("Sunn"),
                new Brand("Sunrise"),
                new Brand("Super Alberti"),
                new Brand("Super Bass"),
                new Brand("Super Salas"),
                new Brand("Super Sensitive"),
                new Brand("Super Stradella"),
                new Brand("Super Vee"),
                new Brand("Supercussion"),
                new Brand("Superlux"),
                new Brand("Supernatural Cymbals"),
                new Brand("Superscope"),
                new Brand("Superslick"),
                new Brand("Supertone"),
                new Brand("Suprem"),
                new Brand("Supro"),
                new Brand("Susato"),
                new Brand("Sutera"),
                new Brand("Suzuki"),
                new Brand("Svetlana"),
                new Brand("Swan Flight"),
                new Brand("Swart Amps"),
                new Brand("SWD SoundWatchingDrum"),
                new Brand("Sweet Pipes"),
                new Brand("Sweet Sound"),
                new Brand("Swefog"),
                new Brand("SwirlyGig"),
                new Brand("Swisson"),
                new Brand("Swissonic"),
                new Brand("Switch Guitars"),
                new Brand("Switchcraft"),
                new Brand("SWR"),
                new Brand("Sx"),
                new Brand("Sylvania"),
                new Brand("Symetrix"),
                new Brand("Synapse Audio"),
                new Brand("Synq"),
                new Brand("Synthesis Technology"),
                new Brand("Synthetic Sound Labs"),
                new Brand("Synthogy"),
                new Brand("T Rex"),
                new Brand("T.bone"),
                new Brand("T.Miranda"),
                new Brand("T.U.K."),
                new Brand("Tabacco"),
                new Brand("Tac Mixers"),
                new Brand("Tacoma"),
                new Brand("TAF Truss Aluminium Factory"),
                new Brand("Tagima"),
                new Brand("Taiki"),
                new Brand("Taiyo Yuden"),
                new Brand("Takamine"),
                new Brand("Takeda Bassoon"),
                new Brand("Takstar"),
                new Brand("Taktell"),
                new Brand("Tama"),
                new Brand("Tamaka"),
                new Brand("Tamaki"),
                new Brand("Tambor"),
                new Brand("Tamburo"),
                new Brand("Tandberg"),
                new Brand("Tanglewood"),
                new Brand("Tannoy"),
                new Brand("Tapco"),
                new Brand("Tapco by Mackie"),
                new Brand("Tapspace Publications"),
                new Brand("TARA LABS"),
                new Brand("Tara Publications"),
                new Brand("TAS"),
                new Brand("Tascam"),
                new Brand("Tasker"),
                new Brand("Tasso Audio"),
                new Brand("Taurus"),
                new Brand("Tayden"),
                new Brand("Tayden Speakers"),
                new Brand("Taye"),
                new Brand("Taylor"),
                new Brand("TC Electronic"),
                new Brand("TC Helicon"),
                new Brand("TCase"),
                new Brand("T-Cymbals"),
                new Brand("TDK"),
                new Brand("TDrum"),
                new Brand("Teac"),
                new Brand("TecAmp"),
                new Brand("Tech 21"),
                new Brand("Technica"),
                new Brand("Technics"),
                new Brand("Technosound"),
                new Brand("Techra"),
                new Brand("Teclumen"),
                new Brand("Tecnare"),
                new Brand("Tecsom"),
                new Brand("Ted Klum"),
                new Brand("Teenage Engineering"),
                new Brand("Tegeler Audio"),
                new Brand("Teisco"),
                new Brand("Teknosign"),
                new Brand("Tekson"),
                new Brand("Teksonor"),
                new Brand("Telefunken"),
                new Brand("Teletronix"),
                new Brand("Telex"),
                new Brand("Tempus Drums"),
                new Brand("Tenayo"),
                new Brand("Tenlux"),
                new Brand("Tennessee"),
                new Brand("Tenson"),
                new Brand("TenTen Devices"),
                new Brand("Teqsas"),
                new Brand("Terada Guitars"),
                new Brand("Terratec"),
                new Brand("TerraTec Producer"),
                new Brand("Terrè"),
                new Brand("Tesla"),
                new Brand("Tesla Audio Lab"),
                new Brand("Teuffel Guitars"),
                new Brand("Texsign"),
                new Brand("Teye Guitars"),
                new Brand("TF Morris"),
                new Brand("TFPro"),
                new Brand("Thalia"),
                new Brand("THD"),
                new Brand("The Box"),
                new Brand("The Brass Spa"),
                new Brand("The Gripp"),
                new Brand("The Hand"),
                new Brand("The Hood"),
                new Brand("The Loar"),
                new Brand("The Music Stamp"),
                new Brand("The Singing Machine"),
                new Brand("The Sssnake"),
                new Brand("The String Centre"),
                new Brand("The T Amp"),
                new Brand("the t.racks"),
                new Brand("The Valve"),
                new Brand("The Voice of Saturn"),
                new Brand("Thema"),
                new Brand("Theo Wanne"),
                new Brand("Theodore Presser"),
                new Brand("Thermionic Culture"),
                new Brand("Third Eye Guitar"),
                new Brand("Third Hand Capo"),
                new Brand("Thomann"),
                new Brand("Thomas"),
                new Brand("Thomas Organs"),
                new Brand("Thomastik"),
                new Brand("Thomastik Infeld"),
                new Brand("Thomson Technologies"),
                new Brand("Thon"),
                new Brand("Thorens"),
                new Brand("ThorpyFX"),
                new Brand("ThreeGuitars"),
                new Brand("Throbak"),
                new Brand("Thud Rumble"),
                new Brand("Thumb Eze"),
                new Brand("Thunder"),
                new Brand("Thunderfunk"),
                new Brand("Thunderplugs"),
                new Brand("Thürmer"),
                new Brand("Timber Tones"),
                new Brand("Timpani"),
                new Brand("Tino Tedesco"),
                new Brand("Tipbook"),
                new Brand("Tiptop Audio"),
                new Brand("Titan Cabs"),
                new Brand("Titan Stage"),
                new Brand("Titanex"),
                new Brand("Tittarelli"),
                new Brand("Tk Audio"),
                new Brand("TKL"),
                new Brand("TKMelody"),
                new Brand("tks Engineering"),
                new Brand("TL Audio"),
                new Brand("TOA Electronics"),
                new Brand("ToadWorks"),
                new Brand("Tobias"),
                new Brand("Toca"),
                new Brand("Toft Audio Designs"),
                new Brand("Together Again"),
                new Brand("Togra"),
                new Brand("Tokai"),
                new Brand("Toledo"),
                new Brand("Tom Anderson Guitars"),
                new Brand("Tom Crown"),
                new Brand("Tom Gauger"),
                new Brand("Tom Holmes"),
                new Brand("Tombo"),
                new Brand("Tom''s Line"),
                new Brand("Tomsline"),
                new Brand("Tone Amps"),
                new Brand("Tone Candy"),
                new Brand("Tone City"),
                new Brand("Tone Gear"),
                new Brand("Tone in Progress"),
                new Brand("Tone King"),
                new Brand("Tonecandy Pedals"),
                new Brand("Toneczar Effects"),
                new Brand("Tonelux"),
                new Brand("TonePros"),
                new Brand("Tonerider"),
                new Brand("ToneRite"),
                new Brand("ToneWoodAmp"),
                new Brand("ToneWorks"),
                new Brand("Tonium"),
                new Brand("Toontrack"),
                new Brand("Topp Pro"),
                new Brand("Toptone"),
                new Brand("Tornado"),
                new Brand("Toro Strings"),
                new Brand("Torque"),
                new Brand("Tortuga Effects"),
                new Brand("Tosco"),
                new Brand("Toshiba"),
                new Brand("Totally Wycked Audio"),
                new Brand("Town Talk"),
                new Brand("Toyo"),
                new Brand("T-Pedals"),
                new Brand("T-Power"),
                new Brand("Traben"),
                new Brand("Trabes"),
                new Brand("Trace Elliot"),
                new Brand("Tradition Guitars"),
                new Brand("Trailer Trash"),
                new Brand("TrainWreck"),
                new Brand("Trance Audio"),
                new Brand("Transcend"),
                new Brand("Transcontinental Music"),
                new Brand("Trantec"),
                new Brand("Traps"),
                new Brand("Traps Drums"),
                new Brand("Traveler"),
                new Brand("Traveler Guitars"),
                new Brand("Travelite"),
                new Brand("Travis Bean"),
                new Brand("Traynor"),
                new Brand("TreeWorks"),
                new Brand("Trench"),
                new Brand("Trep"),
                new Brand("Trevor James"),
                new Brand("T-Rex"),
                new Brand("Trexist"),
                new Brand("Triad"),
                new Brand("Tribe Guitars"),
                new Brand("Tribute by G&amp;L"),
                new Brand("Trick"),
                new Brand("Trident"),
                new Brand("Trigger Perfect"),
                new Brand("Triggs Guitars"),
                new Brand("Tritonlab"),
                new Brand("Trixon"),
                new Brand("Trizio"),
                new Brand("Trombotine"),
                new Brand("Tromsa"),
                new Brand("Tronical"),
                new Brand("Tronographic"),
                new Brand("Trophy"),
                new Brand("True Systems"),
                new Brand("True Temperament"),
                new Brand("Truetone"),
                new Brand("TrumCor"),
                new Brand("Trusst"),
                new Brand("Truth Custom Drums"),
                new Brand("Trutone"),
                new Brand("TRX Cymbals"),
                new Brand("Tsa Tecnology"),
                new Brand("TT-Cabs"),
                new Brand("TTM Guitars"),
                new Brand("Tube Amp Doctor"),
                new Brand("Tube Tech"),
                new Brand("Tube Works"),
                new Brand("Tube-Town"),
                new Brand("Tune"),
                new Brand("Tung Sol"),
                new Brand("Tungsram"),
                new Brand("TurboSound"),
                new Brand("Turkish Cymbals"),
                new Brand("Turkistan"),
                new Brand("Tuscany"),
                new Brand("TusQ"),
                new Brand("Tutondo"),
                new Brand("Tuyama"),
                new Brand("TV Jones"),
                new Brand("TWA Fly Boys"),
                new Brand("Twisted-Electrons"),
                new Brand("Two Notes"),
                new Brand("Two-Rock"),
                new Brand("Tycoon Percussion"),
                new Brand("Tyler Guitars"),
                new Brand("U &amp; I Software"),
                new Brand("U.S. Masters"),
                new Brand("UDG"),
                new Brand("UDG Ultimate DJ Gear"),
                new Brand("Udrum"),
                new Brand("Ueberschall"),
                new Brand("UFIP"),
                new Brand("Uher"),
                new Brand("Ultimate"),
                new Brand("Ultimate Ears"),
                new Brand("Ultimate Sound Bank"),
                new Brand("Ultimate Support"),
                new Brand("Ultra"),
                new Brand("Ultracase"),
                new Brand("Ultrasone"),
                new Brand("UltraSound"),
                new Brand("Unbranded"),
                new Brand("Underwood"),
                new Brand("Unison Research"),
                new Brand("United Labels"),
                new Brand("Unity Audio"),
                new Brand("Universal Audio"),
                new Brand("Universal Percussion"),
                new Brand("Univox"),
                new Brand("Up Stage"),
                new Brand("Urei"),
                new Brand("US Blaster"),
                new Brand("USA Custom Guitars"),
                new Brand("Use Audio"),
                new Brand("Utah Speaker"),
                new Brand("Vact"),
                new Brand("Vader Cabinets"),
                new Brand("Vahlbruch"),
                new Brand("Valco"),
                new Brand("Valencia Guitars"),
                new Brand("Valenti guitars"),
                new Brand("Valentino"),
                new Brand("Valeton"),
                new Brand("Valley Arts"),
                new Brand("Valley People"),
                new Brand("Valmusic"),
                new Brand("ValveTech Amps"),
                new Brand("ValveTrain Amplification"),
                new Brand("Valvolare"),
                new Brand("Van Den Hul"),
                new Brand("Van Kleef"),
                new Brand("Van Zandt"),
                new Brand("Van-Amps"),
                new Brand("Vanderkley"),
                new Brand("Vandoren"),
                new Brand("Vantage"),
                new Brand("Vantage Guitars"),
                new Brand("Var Ance"),
                new Brand("Varta"),
                new Brand("Varytec"),
                new Brand("Vater"),
                new Brand("VDL Professional Analogics"),
                new Brand("Vecchio"),
                new Brand("Veelah Guitars"),
                new Brand("Vega"),
                new Brand("Velodyne Acoustics"),
                new Brand("Velvet Strings"),
                new Brand("Vemuram"),
                new Brand("Venson"),
                new Brand("Venus Flutes"),
                new Brand("Verbatim"),
                new Brand("Verbos"),
                new Brand("Verde Fisarmoniche"),
                new Brand("Vermona"),
                new Brand("Verse"),
                new Brand("Vertex Effects"),
                new Brand("Vesta Fire"),
                new Brand("Vestax"),
                new Brand("Vester"),
                new Brand("VF Guitar Works"),
                new Brand("VFE Pedals"),
                new Brand("Vgs Guitars"),
                new Brand("VGV"),
                new Brand("VHT"),
                new Brand("Vibe Drum"),
                new Brand("Vibesware"),
                new Brand("Vibramate"),
                new Brand("Vibrato Sax"),
                new Brand("Vibrawell"),
                new Brand("Vic Firth"),
                new Brand("Vicente Tatay Tomas"),
                new Brand("Vick Audio"),
                new Brand("Vicoustic"),
                new Brand("Victoria Accordions"),
                new Brand("Victoria Amps"),
                new Brand("Victory Amplifiers"),
                new Brand("Vienna Instruments"),
                new Brand("Vieta"),
                new Brand("Vig"),
                new Brand("Vigier Guitars"),
                new Brand("Vignoni Accordions"),
                new Brand("Villex"),
                new Brand("Vimar"),
                new Brand("Vince"),
                new Brand("Vinetto"),
                new Brand("Vintage"),
                new Brand("Vintech"),
                new Brand("Vinteck"),
                new Brand("Violet Audio"),
                new Brand("Violet Design"),
                new Brand("Vir2"),
                new Brand("VirSyn"),
                new Brand("Viscount"),
                new Brand("Vision"),
                new Brand("Visual Circuit"),
                new Brand("Visual Sound"),
                new Brand("Vital Arts"),
                new Brand("Vito"),
                new Brand("Vitoos"),
                new Brand("Vivanco"),
                new Brand("VMB"),
                new Brand("V-Moda"),
                new Brand("Vocal Power Institute"),
                new Brand("Voce inc."),
                new Brand("VocoPro"),
                new Brand("Voes"),
                new Brand("Vogel''s"),
                new Brand("Voice System"),
                new Brand("Void"),
                new Brand("Volcano"),
                new Brand("Volontè &amp; Co"),
                new Brand("Volume Drums"),
                new Brand("Vonyx"),
                new Brand("VooDoo"),
                new Brand("Voodoo Lab"),
                new Brand("Vortex Italy"),
                new Brand("Vovox"),
                new Brand("Vox"),
                new Brand("Vox Meister"),
                new Brand("Voyage Air Guitars"),
                new Brand("VPI"),
                new Brand("VSCASES"),
                new Brand("VTG"),
                new Brand("Vulcan Cymbal"),
                new Brand("W.D. Brand"),
                new Brand("Wailer"),
                new Brand("Wal"),
                new Brand("Walden"),
                new Brand("Waldorf"),
                new Brand("Walkasse"),
                new Brand("Wallacher"),
                new Brand("Walrus Audio"),
                new Brand("Walrus Productions"),
                new Brand("Walter Franchi Liutaio"),
                new Brand("Walter Nirschl"),
                new Brand("Walter Woods"),
                new Brand("Walther"),
                new Brand("Walton Music"),
                new Brand("Waltons"),
                new Brand("Wampler Pedals"),
                new Brand("Wandre"),
                new Brand("Warburton"),
                new Brand("Warehouse Flightcase"),
                new Brand("Warehouse Guitar Speakers"),
                new Brand("Warm Audio"),
                new Brand("Warmoth"),
                new Brand("Warner Bros"),
                new Brand("Warr Guitar"),
                new Brand("Warriors"),
                new Brand("Warwick"),
                new Brand("Washburn"),
                new Brand("Waterfall Audio"),
                new Brand("Waterstone"),
                new Brand("Watson Guptill"),
                new Brand("Wattson FX"),
                new Brand("W-AUDIO"),
                new Brand("Wave Arts"),
                new Brand("Wave Machine Labs"),
                new Brand("Wave Panels"),
                new Brand("Waveelite"),
                new Brand("Waves"),
                new Brand("Wavetrap"),
                new Brand("Way Huge"),
                new Brand("Way Huge Electronics"),
                new Brand("Way Out Ware"),
                new Brand("WBS"),
                new Brand("Wcr Guitar Pickups"),
                new Brand("WD Music"),
                new Brand("Weapon"),
                new Brand("Weapon Guitars"),
                new Brand("Weber"),
                new Brand("Weber &amp; Son"),
                new Brand("Weber Speakers"),
                new Brand("Wechter"),
                new Brand("Wedge"),
                new Brand("Wee Lush FX"),
                new Brand("Weinbach"),
                new Brand("Weisbach"),
                new Brand("Weiss"),
                new Brand("Weissenborn"),
                new Brand("Welson"),
                new Brand("Weltklang"),
                new Brand("Weltmeister"),
                new Brand("Wem"),
                new Brand("Weril"),
                new Brand("Wersi"),
                new Brand("Wes Audio"),
                new Brand("Wesc"),
                new Brand("Wesley"),
                new Brand("Westbury"),
                new Brand("Westelettric"),
                new Brand("Westlake Audio"),
                new Brand("Westone"),
                new Brand("WGS"),
                new Brand("Whacky Music"),
                new Brand("Wharfedale"),
                new Brand("Wharfedale Pro"),
                new Brand("Whirlwind"),
                new Brand("WhisperRoom"),
                new Brand("White Instruments"),
                new Brand("Widara"),
                new Brand("Wilhsteinberg"),
                new Brand("Wilkinson"),
                new Brand("Willcox Guitars"),
                new Brand("Willermann"),
                new Brand("William Horn"),
                new Brand("William Lewis &amp; Son"),
                new Brand("Williams"),
                new Brand("Willows Guitar Works"),
                new Brand("Willson"),
                new Brand("Willy Wolf"),
                new Brand("Wilson Brothers"),
                new Brand("Wilson Effects"),
                new Brand("Wincent"),
                new Brand("Windmill"),
                new Brand("Windreed Solution"),
                new Brand("Windy City"),
                new Brand("WIRELESS SOLUTION"),
                new Brand("Wirething"),
                new Brand("WISDOM"),
                new Brand("Wise Publications"),
                new Brand("Wisemann"),
                new Brand("Wisycom"),
                new Brand("Wittner"),
                new Brand("Wizard Amplification"),
                new Brand("Wizoo"),
                new Brand("Wizz Pickups"),
                new Brand("WMD"),
                new Brand("Wolf Guitars"),
                new Brand("WolfeTone"),
                new Brand("Wolfpak"),
                new Brand("Wood &amp; Tronics"),
                new Brand("Wooding"),
                new Brand("Woodstock"),
                new Brand("Word Music"),
                new Brand("Work"),
                new Brand("World Tour"),
                new Brand("World Wide Woodshed"),
                new Brand("WorldMax"),
                new Brand("WorldSonic"),
                new Brand("Worship Together"),
                new Brand("Wrangler"),
                new Brand("Wrap N Strap"),
                new Brand("Wren and Cuff"),
                new Brand("Writer''s Digest"),
                new Brand("Wsl Guitars"),
                new Brand("Wuhan"),
                new Brand("Wunder Audio"),
                new Brand("Wurlitzer"),
                new Brand("Wylde Audio"),
                new Brand("X2 Digital"),
                new Brand("X2 Digital Wireless"),
                new Brand("Xander Electronics"),
                new Brand("Xaoc Devices"),
                new Brand("Xavier Guitars"),
                new Brand("X-Drum"),
                new Brand("Xilica"),
                new Brand("XL Specialty Percussion"),
                new Brand("X-LEAD"),
                new Brand("XLNT Idea"),
                new Brand("Xm"),
                new Brand("Xotic"),
                new Brand("XP Sound"),
                new Brand("XPAudio-Morpheus"),
                new Brand("XP-Cases"),
                new Brand("XS Percussion"),
                new Brand("XTA Electronics"),
                new Brand("X-Treme"),
                new Brand("XTS - XAct Tone Solutions"),
                new Brand("XVive"),
                new Brand("XXL Inside"),
                new Brand("Yairi"),
                new Brand("Yak Pak"),
                new Brand("Yamaha"),
                new Brand("Yanagisawa"),
                new Brand("Yankee"),
                new Brand("Yaqin"),
                new Brand("Yellow Tools"),
                new Brand("Yellowtec"),
                new Brand("Yerasov"),
                new Brand("Yorkville"),
                new Brand("Young Chang"),
                new Brand("YouRock Guitar"),
                new Brand("Yukawa"),
                new Brand("Yuwin"),
                new Brand("Z.Cat Pedals"),
                new Brand("Zacks"),
                new Brand("Zacros Engineering"),
                new Brand("Zagar"),
                new Brand("Zanki"),
                new Brand("Zaor"),
                new Brand("Zar"),
                new Brand("Zebracase"),
                new Brand("Zeck Audio"),
                new Brand("Zeff Wind Instruments"),
                new Brand("Zemaitis"),
                new Brand("Zen Guitars"),
                new Brand("Zen Music"),
                new Brand("Zendrum"),
                new Brand("Zen-on"),
                new Brand("Zerberus Guitars"),
                new Brand("Zero G"),
                new Brand("Zero88"),
                new Brand("ZeroGravity"),
                new Brand("ZeroPik"),
                new Brand("ZeroSette"),
                new Brand("Zeus Cymbal"),
                new Brand("Zildjian"),
                new Brand("Zilla Cabs"),
                new Brand("Zimmermann"),
                new Brand("Zinky"),
                new Brand("Zinner"),
                new Brand("Zinzi"),
                new Brand("Zion Guitars"),
                new Brand("ZIVIK"),
                new Brand("ZMB Professional Audio"),
                new Brand("Zomo"),
                new Brand("Zon"),
                new Brand("Zonda"),
                new Brand("Zoom"),
                new Brand("ZT Amplifiers"),
                new Brand("Zultan"),
                new Brand("Zvex"),
                new Brand("Z-Vex Effects"),
                new Brand("ZZIPP"),
                new Brand("ZZYZX")
        );
    }
}
