package com.giga.museek.bootstrap;

import com.giga.museek.documents.Brand;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class BrandLists {
    private  List<Brand> brands;
    public BrandLists() {
        brands = fillAllBrands1();

    }

    private List<Brand> fillAllBrands1() {

        return List.of(
                new Brand("10mfan"),
                new Brand("2Box"),
                new Brand("3Leaf Audio"),
                new Brand("3rd Power Amplification"),
                new Brand("4MS"),
                new Brand("65 Amps"),
                new Brand("A Data"),
                new Brand("A Designs"),
                new Brand("A Little Thunder"),
                new Brand("AA Alfred &amp; Arno Arnold"),
                new Brand("Aalberg Audio"),
                new Brand("Aardvark"),
                new Brand("Aaxtech"),
                new Brand("AB"),
                new Brand("Abel Axe Guitars"),
                new Brand("Ableton"),
                new Brand("Abm"),
                new Brand("Absolute"),
                new Brand("Absolutely Analog"),
                new Brand("Abstrakt Instruments"),
                new Brand("Ac Cetera"),
                new Brand("Academy"),
                new Brand("Access"),
                new Brand("Accugroove"),
                new Brand("Accuphase"),
                new Brand("Accutronics"),
                new Brand("Ace"),
                new Brand("Acer"),
                new Brand("Acidlab"),
                new Brand("Acme"),
                new Brand("Acorn Instruments"),
                new Brand("Acoustic"),
                new Brand("Acoustic Image"),
                new Brand("Acoustic Line"),
                new Brand("Acoustic Research"),
                new Brand("Acoustica"),
                new Brand("Acoustical"),
                new Brand("Acronn"),
                new Brand("Acronova"),
                new Brand("ActitoN"),
                new Brand("Active"),
                new Brand("Acus"),
                new Brand("Ada"),
                new Brand("ADAM Audio"),
                new Brand("Adam Hall"),
                new Brand("ADAM Professional Audio"),
                new Brand("Adamas"),
                new Brand("Adamovic"),
                new Brand("Adams"),
                new Brand("Adams Media"),
                new Brand("Adamson"),
                new Brand("ADB"),
                new Brand("ADC Equalizer"),
                new Brand("Adcom"),
                new Brand("ADD+"),
                new Brand("ADK"),
                new Brand("Admira"),
                new Brand("Adobe"),
                new Brand("Adonis"),
                new Brand("ADS Tech"),
                new Brand("Advance Acoustic"),
                new Brand("Advance Tube Technology"),
                new Brand("Advanced Audio"),
                new Brand("Advent"),
                new Brand("Aegidius Klotz"),
                new Brand("AER"),
                new Brand("Aerial 7"),
                new Brand("Aero Pickup"),
                new Brand("Aerodrums"),
                new Brand("Aeron"),
                new Brand("AEV"),
                new Brand("AFX Light"),
                new Brand("Agean Cymbals"),
                new Brand("Agile Guitars"),
                new Brand("Agner Drumsticks"),
                new Brand("Agostin Custom Guitars"),
                new Brand("Aguilar"),
                new Brand("Ahead"),
                new Brand("Ahlborn Organs"),
                new Brand("AIAIAI"),
                new Brand("Air Cell"),
                new Brand("Airline"),
                new Brand("AirTurn"),
                new Brand("Aiwa"),
                new Brand("Aizen"),
                new Brand("Akai"),
                new Brand("AKG"),
                new Brand("AKG Acoustics"),
                new Brand("Akiyama"),
                new Brand("Al Cass"),
                new Brand("Alan Wilcox"),
                new Brand("Alaska Pik"),
                new Brand("Alba Guitars"),
                new Brand("Albarry"),
                new Brand("Albert &amp; Mueller"),
                new Brand("Albert Fahr"),
                new Brand("Albert Rieder"),
                new Brand("Alberti"),
                new Brand("Albion"),
                new Brand("Alchemy Cymbals"),
                new Brand("Alctron Electronics"),
                new Brand("Alden Guitars"),
                new Brand("AlecB"),
                new Brand("Alegree"),
                new Brand("Aleho"),
                new Brand("Aleken Games"),
                new Brand("Alembic"),
                new Brand("Alesa Banjos"),
                new Brand("Alesis"),
                new Brand("Alessandro High-End Products"),
                new Brand("Alessi Vacchiano"),
                new Brand("Alexander Mainz"),
                new Brand("Alexandria Percussion"),
                new Brand("Alfred"),
                new Brand("Alhambra"),
                new Brand("Alice"),
                new Brand("Alisyn"),
                new Brand("All Parts"),
                new Brand("All Parts Wood"),
                new Brand("AllDSP"),
                new Brand("Allen &amp; Heath"),
                new Brand("Alleva Coppolo"),
                new Brand("Alliance"),
                new Brand("Allora"),
                new Brand("ALM"),
                new Brand("Alma Electronics Pedals"),
                new Brand("Almansa"),
                new Brand("Alonso Le Dosseur"),
                new Brand("Alparizio Palma"),
                new Brand("Alpha Audio"),
                new Brand("Alpha Recording System"),
                new Brand("Alpine"),
                new Brand("Altair"),
                new Brand("Altamira Guitars"),
                new Brand("Altec Lansing"),
                new Brand("Alter Ego"),
                new Brand("Alternate Mode"),
                new Brand("Altieri"),
                new Brand("Altitude Digital"),
                new Brand("Alto"),
                new Brand("Alto Ritmo"),
                new Brand("Altus Flutes"),
                new Brand("Alumabass"),
                new Brand("Alusonic"),
                new Brand("Alutek"),
                new Brand("Alva"),
                new Brand("Alvarez"),
                new Brand("Alvaro"),
                new Brand("Alysee"),
                new Brand("AM amplification"),
                new Brand("AM Audio"),
                new Brand("AM Mouthpieces"),
                new Brand("Amabilia"),
                new Brand("Amadeus Press"),
                new Brand("Amalfitano Pickups"),
                new Brand("Amat"),
                new Brand("Amati"),
                new Brand("Ambassador"),
                new Brand("Amber Pickups"),
                new Brand("Amborg"),
                new Brand("AMC"),
                new Brand("Amedia"),
                new Brand("Amek"),
                new Brand("American Audio"),
                new Brand("American DJ"),
                new Brand("American Drum"),
                new Brand("American Recorder"),
                new Brand("Amistar"),
                new Brand("Amlux"),
                new Brand("Ammoon"),
                new Brand("Ampeg"),
                new Brand("Ampete"),
                new Brand("Ampex"),
                new Brand("Amphenol"),
                new Brand("Amphion"),
                new Brand("Amplified Nation"),
                new Brand("Amplilux"),
                new Brand("Amplirec"),
                new Brand("AMPTECH"),
                new Brand("AmpTone lab"),
                new Brand("Amptown Cases"),
                new Brand("Amptweaker"),
                new Brand("Ampwedge"),
                new Brand("AMS Neve"),
                new Brand("Amsco"),
                new Brand("AMT Electronics"),
                new Brand("Analog Man"),
                new Brand("Analog Way"),
                new Brand("Analogue Addicts"),
                new Brand("Analogue Solutions"),
                new Brand("Analogue Systems"),
                new Brand("Analysis Plus"),
                new Brand("Anamod"),
                new Brand("Anasound"),
                new Brand("Anatek"),
                new Brand("Anatolian"),
                new Brand("Anchor Audio"),
                new Brand("Andersen Stringed Instruments"),
                new Brand("Andino"),
                new Brand("Andrea Tacchi"),
                new Brand("Andreas Guitars"),
                new Brand("Anelli Cremona"),
                new Brand("Angel"),
                new Brand("Anolis"),
                new Brand("ANT - Advanced Native Technologies"),
                new Brand("Antares"),
                new Brand("Antari"),
                new Brand("Antelope"),
                new Brand("Anthony DeMaria Labs"),
                new Brand("Antigua Casa Nunez"),
                new Brand("Antigua Winds"),
                new Brand("Antoine Courtois"),
                new Brand("Antonelli"),
                new Brand("Antonio Aparicio"),
                new Brand("Antonio Carvalho"),
                new Brand("Antonio Hermosa"),
                new Brand("Antonio Lorca"),
                new Brand("Antonio Picado"),
                new Brand("Antonio Scandurra"),
                new Brand("Antoniotsai Guitars"),
                new Brand("aNueNue"),
                new Brand("Anygig"),
                new Brand("Anyware Instruments"),
                new Brand("AP Audio"),
                new Brand("Apart"),
                new Brand("Apc"),
                new Brand("Apex"),
                new Brand("Apextone"),
                new Brand("Aphex"),
                new Brand("Api"),
                new Brand("Apogee"),
                new Brand("Apogeo"),
                new Brand("Apollo"),
                new Brand("Applause"),
                new Brand("Applause by Ovation"),
                new Brand("Apple"),
                new Brand("Apple Creek"),
                new Brand("Applied Acoustic System"),
                new Brand("Applied Acoustics Systems"),
                new Brand("Applied Microphone Technology"),
                new Brand("Aquarian"),
                new Brand("AquilaSax"),
                new Brand("AR Resonance"),
                new Brand("AR Resonnace"),
                new Brand("Aragona"),
                new Brand("Aram Music"),
                new Brand("Aramat effects"),
                new Brand("Aranjuez"),
                new Brand("Arbiter Flats"),
                new Brand("ARC Effects"),
                new Brand("Arcam"),
                new Brand("Arcane Inc Pickups"),
                new Brand("Arcangeli Guitars"),
                new Brand("Archimede Diffusori"),
                new Brand("area-mic"),
                new Brand("Argosy Console"),
                new Brand("Aria"),
                new Brand("Aries"),
                new Brand("Arion"),
                new Brand("Arirang"),
                new Brand("Ariston Castelfidardo"),
                new Brand("Arkaos"),
                new Brand("Armas"),
                new Brand("Armin &amp; Mario GROPP"),
                new Brand("Armin Hanika"),
                new Brand("Armstrong"),
                new Brand("Arnolds &amp; Sons"),
                new Brand("Aroma"),
                new Brand("Arp"),
                new Brand("Arrel Audio"),
                new Brand("Arriba Cases"),
                new Brand("Arrow"),
                new Brand("ART"),
                new Brand("Art &amp; Lutherie"),
                new Brand("Art Select"),
                new Brand("Astera"),
                new Brand("Aston"),
                new Brand("Asturias Guitars"),
                new Brand("Asus"),
                new Brand("Asymmetric"),
                new Brand("Atari"),
                new Brand("ATC"),
                new Brand("Atelier Z"),
                new Brand("Atlas"),
                new Brand("Atomic Amps"),
                new Brand("Atomic Pro"),
                new Brand("Atomic4dj"),
                new Brand("ATP"),
                new Brand("Atrics guitars"),
                new Brand("ATS"),
                new Brand("Attack"),
                new Brand("Audac"),
                new Brand("Audax"),
                new Brand("Audere"),
                new Brand("Audes"),
                new Brand("Audeze"),
                new Brand("Audient"),
                new Brand("Audilaza"),
                new Brand("Audinate"),
                new Brand("Audio Accessories"),
                new Brand("Audio Analogue"),
                new Brand("Audio Damage"),
                new Brand("Audio Definition"),
                new Brand("Audio Developments"),
                new Brand("Audio Innovate"),
                new Brand("Audio Logic"),
                new Brand("Audio Performance"),
                new Brand("Audio Research"),
                new Brand("Audio Solution"),
                new Brand("Audio Technica"),
                new Brand("Audio Tools"),
                new Brand("Audiodesign Pro"),
                new Brand("AudioFactory"),
                new Brand("Audiofilia"),
                new Brand("Audioline"),
                new Brand("AudioLive"),
                new Brand("Audiomarine"),
                new Brand("Audiometric"),
                new Brand("Audiophony"),
                new Brand("AUDIOPROBE"),
                new Brand("Audioquest"),
                new Brand("Audioromance Cables"),
                new Brand("Audioscope"),
                new Brand("Audiosir"),
                new Brand("Audiostatic"),
                new Brand("Audiotrak"),
                new Brand("AudioWarrior"),
                new Brand("Audison"),
                new Brand("Audition"),
                new Brand("Audix"),
                new Brand("August Forster"),
                new Brand("Augustine"),
                new Brand("Aulos"),
                new Brand("Auna"),
                new Brand("Aune Audio"),
                new Brand("Auralex"),
                new Brand("Auratone"),
                new Brand("Austin Custom Brass"),
                new Brand("Australian Monitor"),
                new Brand("Automatic Cases"),
                new Brand("Autosonik"),
                new Brand("AV"),
                new Brand("AV Link"),
                new Brand("Avalon"),
                new Brand("Avant Electronics"),
                new Brand("Avantone"),
                new Brand("Avid"),
                new Brand("Aviom"),
                new Brand("Avolites"),
                new Brand("Axcess by Giannini"),
                new Brand("Axesrus"),
                new Brand("Axess Electronics"),
                new Brand("AxeTrak"),
                new Brand("Axis"),
                new Brand("Axl"),
                new Brand("Axtech"),
                new Brand("Axys"),
                new Brand("Ayers"),
                new Brand("Ayotte"),
                new Brand("Ayotte Drums"),
                new Brand("Azden"),
                new Brand("Azumi"),
                new Brand("B 52"),
                new Brand("B Band"),
                new Brand("B&amp;C Speakers"),
                new Brand("B&amp;G Guitars"),
                new Brand("B&amp;J Serenader"),
                new Brand("B&amp;K"),
                new Brand("B&amp;L battere&amp;levare"),
                new Brand("B&amp;S"),
                new Brand("B.C. Rich"),
                new Brand("B.Jacoby Guitars"),
                new Brand("B2 Effetti"),
                new Brand("Ba.Ma Tralicci"),
                new Brand("Babicz"),
                new Brand("Bacchi tecnologie audio"),
                new Brand("Bacchus"),
                new Brand("Bach"),
                new Brand("Bachmann"),
                new Brand("Backbeat"),
                new Brand("Backline"),
                new Brand("Backun"),
                new Brand("Backvox"),
                new Brand("Bad Cat"),
                new Brand("Baden Guitars"),
                new Brand("Bae"),
                new Brand("Bag End"),
                new Brand("Bakers Guitars"),
                new Brand("Balbex Drumsticks"),
                new Brand("Baldwin Piano"),
                new Brand("Balken"),
                new Brand("Ballone Burini"),
                new Brand("Balthur"),
                new Brand("Bam Cases"),
                new Brand("Bama"),
                new Brand("Bang &amp; Olufsen"),
                new Brand("Banners"),
                new Brand("Banzai Music"),
                new Brand("Barber"),
                new Brand("Barbetta"),
                new Brand("Barco"),
                new Brand("Barcus Berry"),
                new Brand("Bardl"),
                new Brand("Bare Knuckle Pickups"),
                new Brand("Barefoot Sound"),
                new Brand("Barge Concepts"),
                new Brand("Bari"),
                new Brand("Bariselli"),
                new Brand("Barock"),
                new Brand("Baroni Lab"),
                new Brand("Barrios Guitars"),
                new Brand("Bartolini Pickups"),
                new Brand("Basement Arts"),
                new Brand("Basf"),
                new Brand("Basic Audio"),
                new Brand("Basix"),
                new Brand("Bass Drum O''s"),
                new Brand("Bassculture"),
                new Brand("BassLab"),
                new Brand("Basslines"),
                new Brand("Basson"),
                new Brand("Bastl"),
                new Brand("Bat Drums"),
                new Brand("Baton Rouge"),
                new Brand("Batteriasound"),
                new Brand("Battiloro"),
                new Brand("Battipenna.it"),
                new Brand("Bauer Percussion"),
                new Brand("Bauhaus Walstein"),
                new Brand("Baxter"),
                new Brand("BBE"),
                new Brand("B-Beng"),
                new Brand("BCGuitars"),
                new Brand("BD-Design"),
                new Brand("Bdx Sound"),
                new Brand("BeamZ"),
                new Brand("Beard"),
                new Brand("Bearfoot FX"),
                new Brand("Beat Up"),
                new Brand("Beatnik"),
                new Brand("Beato"),
                new Brand("Beats"),
                new Brand("Bechstein"),
                new Brand("Beckemer"),
                new Brand("Bedell Guitars"),
                new Brand("Bedrock"),
                new Brand("Beechler"),
                new Brand("Beetronics"),
                new Brand("Behringer"),
                new Brand("Belcat"),
                new Brand("Belkin"),
                new Brand("Bell"),
                new Brand("Bellafina"),
                new Brand("Bellari"),
                new Brand("Belltron"),
                new Brand("Bellucci"),
                new Brand("Belmonte"),
                new Brand("Beltrami Fisarmoniche"),
                new Brand("Beltuna"),
                new Brand("Ben Rod"),
                new Brand("Benavente"),
                new Brand("Benchmark"),
                new Brand("Benedetto"),
                new Brand("Benge"),
                new Brand("Benq"),
                new Brand("Benson"),
                new Brand("Bentley Pianos"),
                new Brand("Berg Larsen"),
                new Brand("Bergantino"),
                new Brand("Bergen"),
                new Brand("Bergerault"),
                new Brand("Bergmann"),
                new Brand("Berklee Press"),
                new Brand("Berkos FX"),
                new Brand("BERP"),
                new Brand("Bespeco"),
                new Brand("Besson"),
                new Brand("Best Brass"),
                new Brand("Best Products"),
                new Brand("Best Service"),
                new Brand("Best Sound"),
                new Brand("Beta Aivin"),
                new Brand("Beta Three"),
                new Brand("Bettermaker"),
                new Brand("Beyer"),
                new Brand("Beyerdynamic"),
                new Brand("Beyma"),
                new Brand("BG"),
                new Brand("Bgw"),
                new Brand("bH Amps"),
                new Brand("Bholand &amp; Fuchs"),
                new Brand("Biamp"),
                new Brand("Biarnel"),
                new Brand("BIAS"),
                new Brand("Biema"),
                new Brand("Big Bang"),
                new Brand("Big Bends"),
                new Brand("Big Dipper"),
                new Brand("Big Fat Snare Drum"),
                new Brand("Big Fish Audio"),
                new Brand("Big Heart Slides"),
                new Brand("Big Joe Stomp Box Company"),
                new Brand("Big John Effects"),
                new Brand("Big Knob Pedals"),
                new Brand("Bigben Interactive"),
                new Brand("Bigfoot FX"),
                new Brand("BigHeart"),
                new Brand("Bigsby"),
                new Brand("Bill Edwards Publishing"),
                new Brand("Bill Lawrence"),
                new Brand("Billboard"),
                new Brand("Billy Boy Guitars"),
                new Brand("Billy Hyde"),
                new Brand("Binak"),
                new Brand("Binson"),
                new Brand("Bioworld"),
                new Brand("Birchwood Casey"),
                new Brand("Bittner"),
                new Brand("Bitwig"),
                new Brand("Bixonic"),
                new Brand("Biyang"),
                new Brand("BJFE"),
                new Brand("BK Butler"),
                new Brand("BKE Technology"),
                new Brand("Black Arts Toneworks"),
                new Brand("Black Case"),
                new Brand("Black Cat Pedals"),
                new Brand("Black Diamond"),
                new Brand("Black Kross"),
                new Brand("Black Label"),
                new Brand("Black Lion Audio"),
                new Brand("Black Star Design"),
                new Brand("Black TusQ"),
                new Brand("Black Volt Amplification"),
                new Brand("Blackheart"),
                new Brand("Blackout Effectors"),
                new Brand("Blackshark"),
                new Brand("Blackstar"),
                new Brand("Blackstone Appliances"),
                new Brand("Blade"),
                new Brand("Blakemore Effects"),
                new Brand("Blakhart"),
                new Brand("Blankenship"),
                new Brand("Blaupunkt"),
                new Brand("Bleep Labs"),
                new Brand("Blessing"),
                new Brand("Blista"),
                new Brand("Blitz"),
                new Brand("Blu Music"),
                new Brand("Blue"),
                new Brand("Blue Juice"),
                new Brand("Blue Sky"),
                new Brand("Blueamps"),
                new Brand("Bluebird ''56 Guitars"),
                new Brand("Bluedio"),
                new Brand("Blueridge"),
                new Brand("Blues Saraceno"),
                new Brand("BluexLab"),
                new Brand("BluGuitar"),
                new Brand("Bluthner"),
                new Brand("BMF"),
                new Brand("BMS Speakers"),
                new Brand("Bo Pep"),
                new Brand("Bob Ackerman"),
                new Brand("Bob McGrath"),
                new Brand("Bob Reeves"),
                new Brand("Bobcat"),
                new Brand("Body Glove"),
                new Brand("Bogart Bass"),
                new Brand("Bogner"),
                new Brand("Bohemia Piano"),
                new Brand("Bohemian Guitars"),
                new Brand("Bois Ligatures"),
                new Brand("Boisselot"),
                new Brand("Bolton"),
                new Brand("Bompezzo"),
                new Brand("Bonade"),
                new Brand("Bond Guitars"),
                new Brand("Bondi Effects"),
                new Brand("Bone Drum"),
                new Brand("Bontempi"),
                new Brand("Boo Instruments"),
                new Brand("Boomerang"),
                new Brand("BoomToneDj"),
                new Brand("Bo-one Guitars"),
                new Brand("Boosey &amp; Co"),
                new Brand("Boosey &amp; Hawkes"),
                new Brand("Borgani"),
                new Brand("Borgna"),
                new Brand("Born to Sing"),
                new Brand("Bornemark"),
                new Brand("Borsini"),
                new Brand("Boschma"),
                new Brand("Bose"),
                new Brand("Bosendorfer"),
                new Brand("Bosh"),
                new Brand("Bosphorus"),
                new Brand("Boss"),
                new Brand("Boston"),
                new Brand("Bosworth"),
                new Brand("Botex"),
                new Brand("Boucher"),
                new Brand("Boulder Creek Guitars"),
                new Brand("Bourgeois Guitars"),
                new Brand("Bowers &amp; Wilkins"),
                new Brand("boxinsonorizzato.it"),
                new Brand("Box-Profi"),
                new Brand("BOXY"),
                new Brand("Bozo Podunavac"),
                new Brand("BPM Studiotechnik"),
                new Brand("Brady"),
                new Brand("Brainwerks"),
                new Brand("Brancher"),
                new Brand("Brand X"),
                new Brand("Brandoni"),
                new Brand("Brannen Cooper"),
                new Brand("Brauner Microphones"),
                new Brand("Bravado"),
                new Brand("Brave Amps"),
                new Brand("Brazen Guitars"),
                new Brand("BRBS Amplification"),
                new Brand("Breach"),
                new Brand("Breath Builder"),
                new Brand("Bredamhill"),
                new Brand("Breedlove"),
                new Brand("Brenn &amp; Sohn"),
                new Brand("Brent Averill"),
                new Brand("Brentwood Benson"),
                new Brand("Breslmair"),
                new Brand("Brian May Guitars"),
                new Brand("Brian Moore"),
                new Brand("Bricasti Design"),
                new Brand("Briccialdi"),
                new Brand("Brice Basses"),
                new Brand("Brilhart"),
                new Brand("Briteq"),
                new Brand("Broadwood &amp; Sons"),
                new Brand("Brodmann"),
                new Brand("Brownsville Guitars"),
                new Brand("Bruck"),
                new Brand("Brunetti"),
                new Brand("Bruno Amp"),
                new Brand("Bruno Tilz"),
                new Brand("Bruno Traverso Guitars"),
                new Brand("BRYCE"),
                new Brand("Bryston"),
                new Brand("BSC Trumpets"),
                new Brand("BSM"),
                new Brand("BSS Audio"),
                new Brand("Bst"),
                new Brand("BSX Bass"),
                new Brand("BSX By Paiste"),
                new Brand("Buchla"),
                new Brand("Budda"),
                new Brand("Buddy Rich Drum Company"),
                new Brand("Buescher"),
                new Brand("Buffalo Fx"),
                new Brand("Buffet Crampon"),
                new Brand("Bugari Armando"),
                new Brand("Bugera"),
                new Brand("Bulgheroni"),
                new Brand("Bulk Sonica"),
                new Brand("Bull"),
                new Brand("Bullet Cables"),
                new Brand("Bundy"),
                new Brand("Burger &amp; Jacobi"),
                new Brand("Burguet"),
                new Brand("Burkart"),
                new Brand("Burkey"),
                new Brand("Burl Audio"),
                new Brand("Burn Fx"),
                new Brand("Burns Guitars"),
                new Brand("Burny"),
                new Brand("Burriss Amps"),
                new Brand("Buscarini"),
                new Brand("Busilacchio"),
                new Brand("Buttarini"),
                new Brand("ButtKicker"),
                new Brand("Buzz Electronics"),
                new Brand("By Marco Fisarmoniche"),
                new Brand("BYOC"),
                new Brand("C Tech"),
                new Brand("C&amp;C Drums"),
                new Brand("C.M. Prestige"),
                new Brand("c.t.e."),
                new Brand("Cabart"),
                new Brand("Cabasse"),
                new Brand("Caber Amplificazioni"),
                new Brand("Cable Corp"),
                new Brand("Cablo Custom"),
                new Brand("Cabotron"),
                new Brand("Cabre"),
                new Brand("CAD"),
                new Brand("Cadac"),
                new Brand("Cadenbach Acoustics"),
                new Brand("Cadeson"),
                new Brand("CAIG"),
                new Brand("Caimbè"),
                new Brand("Cajon"),
                new Brand("Cajon Rock"),
                new Brand("Cajonrock"),
                new Brand("Cakewalk"),
                new Brand("Cal Mil"),
                new Brand("Calace"),
                new Brand("Calato"),
                new Brand("Caliber Guitars"),
                new Brand("Calicchio"),
                new Brand("Caline"),
                new Brand("Calisia"),
                new Brand("Callaham"),
                new Brand("Callet Trumpets"),
                new Brand("Calrec Audio"),
                new Brand("Calsbro"),
                new Brand("Calton Cases"),
                new Brand("Camac"),
                new Brand("Camarota Basses &amp; Guitars"),
                new Brand("Camber"),
                new Brand("Cambridge Audio"),
                new Brand("Cambridge SoundWorks"),
                new Brand("Camco"),
                new Brand("Cameo"),
                new Brand("Camillo Perrella"),
                new Brand("Campbell American Guitars"),
                new Brand("Camps"),
                new Brand("Canare"),
                new Brand("Cannon Electric"),
                new Brand("Cannon Percussion"),
                new Brand("Cannonball"),
                new Brand("Canon"),
                new Brand("Canopus Drums"),
                new Brand("Cantini Strings"),
                new Brand("Canto"),
                new Brand("Canton"),
                new Brand("Cantulia"),
                new Brand("Capa"),
                new Brand("Caparison Guitars"),
                new Brand("Capek"),
                new Brand("Capsound"),
                new Brand("Carbondix"),
                new Brand("Carboni"),
                new Brand("Carbostick"),
                new Brand("Cardinal Instruments"),
                new Brand("Cardinali"),
                new Brand("Career"),
                new Brand("Carella Guitars"),
                new Brand("Caremi"),
                new Brand("Cargoleni"),
                new Brand("Carisch"),
                new Brand("Carl Fischer"),
                new Brand("Carl Martin"),
                new Brand("Carlo Giordano"),
                new Brand("Carlo Robelli"),
                new Brand("Carl''s Custom Guitars"),
                new Brand("Carlsbro"),
                new Brand("Carlton"),
                new Brand("Carmelo Catania"),
                new Brand("Carol"),
                new Brand("Carol Brass"),
                new Brand("Carol-Ann Amplifiers"),
                new Brand("Caroline Guitar Company"),
                new Brand("Carr Amplifiers"),
                new Brand("Cartec Audio"),
                new Brand("Carter"),
                new Brand("Carver Amplifier"),
                new Brand("Carvin"),
                new Brand("Casio"),
                new Brand("Castagnari"),
                new Brand("Castley"),
                new Brand("Catalinbread"),
                new Brand("Catalyst"),
                new Brand("C-Audio"),
                new Brand("Cav Audio"),
                new Brand("Cavagnolo"),
                new Brand("Cavicchi"),
                new Brand("Cayin"),
                new Brand("Cayman"),
                new Brand("CB Drums"),
                new Brand("CB Percussion"),
                new Brand("CBI"),
                new Brand("Cdrum"),
                new Brand("C-ducer"),
                new Brand("Celemony"),
                new Brand("Celestion"),
                new Brand("Centent Cymbals"),
                new Brand("Center Pitch"),
                new Brand("Centerstream"),
                new Brand("CEntrance"),
                new Brand("Century Drums"),
                new Brand("Ceriatone"),
                new Brand("Cerveny"),
                new Brand("Cerwin Vega"),
                new Brand("Cesva"),
                new Brand("CG Mouthpiece"),
                new Brand("Challen &amp; Son"),
                new Brand("Chameleon Labs"),
                new Brand("ChamSys"),
                new Brand("Chandler"),
                new Brand("Chandler Limited"),
                new Brand("Changye"),
                new Brand("CHAOS.5"),
                new Brand("Chapman Guitars"),
                new Brand("Chapman Stick"),
                new Brand("Chappell"),
                new Brand("Chario"),
                new Brand("Charles Bassoux"),
                new Brand("Charles Bay"),
                new Brand("Charlie Lab"),
                new Brand("Charon"),
                new Brand("Chartbuster"),
                new Brand("CharterOak Acoustic"),
                new Brand("Charvel"),
                new Brand("Chase Bliss Audio"),
                new Brand("Chase Tone"),
                new Brand("Chatelier"),
                new Brand("Chauvet"),
                new Brand("Cheetah"),
                new Brand("Chennel"),
                new Brand("Cheri"),
                new Brand("Cherny"),
                new Brand("Cherry Lane"),
                new Brand("Cherry Music"),
                new Brand("Cherrystone Bass"),
                new Brand("Cherub"),
                new Brand("Cheval Guitars"),
                new Brand("Chevin"),
                new Brand("Chevin Research"),
                new Brand("Chiayo"),
                new Brand("Chicago Blues Box"),
                new Brand("Chicago Iron"),
                new Brand("ChickenPicks"),
                new Brand("Chickering"),
                new Brand("Chieftain"),
                new Brand("Children''s Book Store"),
                new Brand("Chonwoo"),
                new Brand("ChopSaver"),
                new Brand("Chowny"),
                new Brand("Chris Campbell Guitars"),
                new Brand("Chroma Caps"),
                new Brand("Chunk Systems"),
                new Brand("Ciare"),
                new Brand("Cicognani"),
                new Brand("Cicolin"),
                new Brand("Cigalini"),
                new Brand("Cigano Guitars"),
                new Brand("Cimar Guitars"),
                new Brand("Cinder Block"),
                new Brand("Cioks"),
                new Brand("Citron Guitars"),
                new Brand("Citronic"),
                new Brand("Clanalog.com"),
                new Brand("Claricord"),
                new Brand("Clarissa"),
                new Brand("Clark Amplification"),
                new Brand("Clarke"),
                new Brand("Clash Guitars"),
                new Brand("Classè Audio"),
                new Brand("Classic Cantabile"),
                new Brand("Claude Lakey"),
                new Brand("Claude Marchand"),
                new Brand("Clavia"),
                new Brand("ClavinPiano"),
                new Brand("Clay Paky"),
                new Brand("Clayton"),
                new Brand("Clear Audio"),
                new Brand("Clear Voice"),
                new Brand("Clearsonic"),
                new Brand("Cleartone"),
                new Brand("Clement"),
                new Brand("Cliff"),
                new Brand("Clifford Essex Music"),
                new Brand("Clifton"),
                new Brand("Clinch FX"),
                new Brand("Cling On"),
                new Brand("CLN Pedalboards"),
                new Brand("Clockaudio"),
                new Brand("Cloe Guitars"),
                new Brand("Cloud Amplifiers"),
                new Brand("Cloud Microphones"),
                new Brand("Cloud Mixer"),
                new Brand("Clover Basses"),
                new Brand("Club Salsa"),
                new Brand("CM Labs"),
                new Brand("Cmatmods"),
                new Brand("CME"),
                new Brand("CMI"),
                new Brand("CNB Cases"),
                new Brand("CoalTone Guitars"),
                new Brand("Cobalt"),
                new Brand("Cobra International"),
                new Brand("Coda Audio"),
                new Brand("Codem Music"),
                new Brand("Coef Lighting"),
                new Brand("Coemar"),
                new Brand("Coffin"),
                new Brand("Coffin Case"),
                new Brand("Cog Effects"),
                new Brand("Cole Clark Guitars"),
                new Brand("Coleman Audio"),
                new Brand("Coles Microphones"),
                new Brand("Colin Goldie"),
                new Brand("Collard &amp; Collard"),
                new Brand("College Sax"),
                new Brand("Colletto"),
                new Brand("Collings"),
                new Brand("Collins"),
                new Brand("Colorsound"),
                new Brand("Columbus Washboard"),
                new Brand("Combs"),
                new Brand("Comet"),
                new Brand("Comfort Strapp"),
                new Brand("Community"),
                new Brand("Compania"),
                new Brand("Compass"),
                new Brand("Compulite"),
                new Brand("Conde Hermanos"),
                new Brand("Condre"),
                new Brand("Conductor"),
                new Brand("Confettishots"),
                new Brand("Conklin"),
                new Brand("Conn"),
                new Brand("Conquest"),
                new Brand("Consoli Pipe Organs"),
                new Brand("Consuelo Lopez"),
                new Brand("Contemporanea Sao Paulo"),
                new Brand("Contest"),
                new Brand("Contreras"),
                new Brand("Control Synthesis"),
                new Brand("Converse"),
                new Brand("Coolsound"),
                new Brand("Cooper FX"),
                new Brand("Cooper Sound"),
                new Brand("Cooperfisa"),
                new Brand("Coopersonic"),
                new Brand("Cooperstand"),
                new Brand("Copilot Fx"),
                new Brand("Coral"),
                new Brand("Cord Lox"),
                new Brand("Cordera"),
                new Brand("Cordial"),
                new Brand("Cordier"),
                new Brand("Cordlox"),
                new Brand("Cordoba"),
                new Brand("Core Equipment"),
                new Brand("CoreX2"),
                new Brand("Corland"),
                new Brand("Cornell"),
                new Brand("Cornford Amps"),
                new Brand("Coron"),
                new Brand("Corsin"),
                new Brand("Cort"),
                new Brand("Cortex"),
                new Brand("Cortez"),
                new Brand("Cosmolight"),
                new Brand("Cosmosound"),
                new Brand("Costalab"),
                new Brand("Couesnon"),
                new Brand("Countryman"),
                new Brand("Courtois"),
                new Brand("Covington Guitar Effects"),
                new Brand("Coxx"),
                new Brand("CP"),
                new Brand("CQuadro Drums"),
                new Brand("Crafter Guitars"),
                new Brand("Crane"),
                new Brand("Crane Song"),
                new Brand("Crate"),
                new Brand("Crave"),
                new Brand("Craviotto"),
                new Brand("Crazy Tube Circuits"),
                new Brand("CRB"),
                new Brand("CreamWare"),
                new Brand("Creation Audio Labs"),
                new Brand("Creative Concepts"),
                new Brand("Art Strings"),
                new Brand("Arta Guban"),
                new Brand("Artcelior"),
                new Brand("Artec"),
                new Brand("Artemis Editions"),
                new Brand("Artesound"),
                new Brand("Artisan")
        );
    }
}
